"use client"

import { useState, useMemo, useCallback, useEffect, useRef } from "react"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { PageWrapper, PageHeader } from "@/components/layout"
import { Mail, FileText, ClipboardList } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { getCurrentOfficeWeek } from "@/lib/meeting-week"
import { buildMeetingDocumentFileName, resolveEffectiveMeetingDateIso } from "@/lib/reports/meeting-date"
import { QUERY_KEYS } from "@/lib/query-keys"
import { toast } from "sonner"
import { RecipientSelector } from "./_components/RecipientSelector"
import { WeeklySummaryForm } from "./_components/WeeklySummaryForm"
import { SchedulingOptions } from "./_components/SchedulingOptions"
import { SendResultPanel } from "./_components/SendResultPanel"
import { SummarySidebarCard } from "./_components/SummarySidebarCard"
import { useWeeklySummarySend } from "./_components/use-weekly-summary-send"

type Employee = {
  id: string
  full_name: string
  company_email: string | null
  additional_email: string | null
  department: string | null
  employment_status: string | null
}

type PresenterRef = {
  id: string
  full_name: string
}

type RecipientMode = "all" | "select" | "manual" | "all_plus" | "resend_missed"
type ContentChoice =
  | "weekly_report"
  | "action_points_autogenerated"
  | "knowledge_sharing_session"
  | "minutes_of_meeting"
type SendTiming = "now" | "scheduled" | "recurring"

type MeetingWeekDocument = {
  id: string
  meeting_week: number
  meeting_year: number
  meeting_date: string | null
  document_type: "knowledge_sharing_session" | "minutes"
  department: string | null
  presenter_id: string | null
  file_name: string
  version_no: number
  is_current: boolean
  signed_url: string | null
  created_at: string
}

type MailDocRef = {
  id: string
  file_name: string
  display_name: string
  /** Signed download URL — used for client-side pre-fetch to avoid edge CPU budget */
  signed_url?: string | null
}

function getFileExtension(fileName: string): string {
  const lower = String(fileName || "").toLowerCase()
  if (lower.endsWith(".pdf")) return "pdf"
  if (lower.endsWith(".docx")) return "docx"
  if (lower.endsWith(".pptx")) return "pptx"
  return "pdf"
}

function buildMeetingDocumentDisplayName(document: MeetingWeekDocument, presenterName?: string | null): string {
  return buildMeetingDocumentFileName({
    documentType: document.document_type,
    meetingDate: document.meeting_date || `${document.meeting_year}-01-01`,
    meetingWeek: document.meeting_week,
    extension: getFileExtension(document.file_name),
    department: document.department,
    presenterName,
  })
}

interface Props {
  employees: Employee[]
  presenterDirectory?: PresenterRef[]
  currentUser?: {
    id: string
    full_name: string | null
    department: string | null
  }
}

function parsePresenterFromKssFileName(fileName: string): string | null {
  const parts = String(fileName || "").split(" - ")
  if (parts.length < 5) return null
  const candidate = parts[2]?.trim() || ""
  if (!candidate || candidate.toLowerCase() === "unknown presenter") return null
  return candidate
}

export function WeeklySummaryContent({ employees, presenterDirectory = [], currentUser }: Props) {
  const supabase = createClient()
  const currentOfficeWeek = getCurrentOfficeWeek()

  // ── State ──────────────────────────────────────────────────────────────────
  const [recipientMode, setRecipientMode] = useState<RecipientMode>("select")
  const [selectedEmployeeIds, setSelectedEmployeeIds] = useState<Set<string>>(new Set())
  const [manualEmails, setManualEmails] = useState<string[]>([])
  const [manualInput, setManualInput] = useState("")
  const [searchQuery, setSearchQuery] = useState("")
  const [deliveredEmailsText, setDeliveredEmailsText] = useState("")

  const [selectedContentChoices, setSelectedContentChoices] = useState<Set<ContentChoice>>(
    new Set<ContentChoice>(["weekly_report"])
  )
  const [selectedPreparedBy, setSelectedPreparedBy] = useState("Terna")

  const currentYear = currentOfficeWeek.year
  const currentWeekNumber = currentOfficeWeek.week
  const [selectedWeeks, setSelectedWeeks] = useState<Set<number>>(() => new Set([currentOfficeWeek.week]))
  const [yearNumber, setYearNumber] = useState(currentYear)

  const [sendTiming, setSendTiming] = useState<SendTiming>("now")
  const [scheduledDate, setScheduledDate] = useState("")
  const [scheduledTime, setScheduledTime] = useState("09:00")
  const [recurringDay, setRecurringDay] = useState("monday")
  const [recurringTime, setRecurringTime] = useState("09:00")
  const hasAppliedDefaultPreparer = useRef(false)

  const queryClient = useQueryClient()

  // ── Fetch active schedules ──────────────────────────────────────────────────
  const { data: activeSchedules = [] } = useQuery({
    queryKey: QUERY_KEYS.adminWeeklySummaryMail(),
    queryFn: async () => {
      const { data, error } = await supabase
        .from("weekly_report_schedules")
        .select("*")
        .eq("is_active", true)
        .order("created_at", { ascending: false })
      if (error) {
        if (error.code === "42P01") return []
        throw new Error(error.message)
      }
      return data || []
    },
  })

  const fetchSchedules = useCallback(() => {
    queryClient.invalidateQueries({ queryKey: QUERY_KEYS.adminWeeklySummaryMail() })
  }, [queryClient])

  // Sorted array of selected weeks (stable reference for queries)
  const sortedSelectedWeeks = useMemo(
    () => (selectedWeeks.size > 0 ? Array.from(selectedWeeks).sort((a, b) => a - b) : [currentWeekNumber]),
    [selectedWeeks, currentWeekNumber]
  )

  // Representative week = smallest selected (used for meeting date label)
  const representativeWeek = sortedSelectedWeeks[0]

  // Fetch docs for ALL selected weeks so the sidebar and send payload are complete
  const { data: allMeetingDocuments = [] } = useQuery({
    queryKey: ["meeting-week-documents-all", sortedSelectedWeeks, yearNumber],
    queryFn: async (): Promise<MeetingWeekDocument[]> => {
      const results = await Promise.all(
        sortedSelectedWeeks.map(async (w) => {
          const res = await fetch(`/api/reports/meeting-week-documents?week=${w}&year=${yearNumber}&currentOnly=true`)
          const payload = await res.json()
          if (!res.ok) return []
          return (payload.data || []) as MeetingWeekDocument[]
        })
      )
      return results.flat()
    },
  })

  const { data: resolvedMeetingDate } = useQuery({
    queryKey: ["meeting-mail-effective-date", representativeWeek, yearNumber],
    queryFn: async () => resolveEffectiveMeetingDateIso(supabase, representativeWeek, yearNumber),
  })

  const toMailDocRef = useCallback(
    (document: MeetingWeekDocument | undefined | null): MailDocRef | null => {
      if (!document) return null
      const presenterName =
        document.presenter_id && document.document_type === "knowledge_sharing_session"
          ? presenterDirectory.find((employee) => employee.id === document.presenter_id)?.full_name ||
            employees.find((employee) => employee.id === document.presenter_id)?.full_name ||
            parsePresenterFromKssFileName(document.file_name) ||
            null
          : null
      return {
        id: document.id,
        file_name: document.file_name,
        display_name: buildMeetingDocumentDisplayName(document, presenterName),
        signed_url: document.signed_url ?? null,
      }
    },
    [employees, presenterDirectory]
  )

  // All KSS docs across all selected weeks (one per week, is_current)
  const allKssDocs = useMemo(
    () =>
      allMeetingDocuments
        .filter((d) => d.document_type === "knowledge_sharing_session" && d.is_current)
        .map((d) => toMailDocRef(d))
        .filter((d): d is MailDocRef => d !== null),
    [allMeetingDocuments, toMailDocRef]
  )

  // All Minutes docs across all selected weeks (one per week, is_current)
  const allMinutesDocs = useMemo(
    () =>
      allMeetingDocuments
        .filter((d) => d.document_type === "minutes" && d.is_current)
        .map((d) => toMailDocRef(d))
        .filter((d): d is MailDocRef => d !== null),
    [allMeetingDocuments, toMailDocRef]
  )

  // currentDocByType: for backward-compat with components that expect a single doc per type
  // Shows representative (first) week's doc for display; full lists go to the send hook
  const currentDocByType = useMemo(
    () => ({
      knowledgeSharingSession: allKssDocs[0] ?? null,
      minutesOfMeeting: allMinutesDocs[0] ?? null,
    }),
    [allKssDocs, allMinutesDocs]
  )

  const autogeneratedActionPointsName = useMemo(
    () =>
      buildMeetingDocumentFileName({
        documentType: "action_points",
        meetingDate: resolvedMeetingDate || `${yearNumber}-01-01`,
        meetingWeek: representativeWeek,
        extension: "pdf",
      }),
    [resolvedMeetingDate, representativeWeek, yearNumber]
  )

  const contentOptions = useMemo(
    () => [
      {
        value: "weekly_report" as ContentChoice,
        label: "Weekly Report",
        icon: FileText,
        desc: "Auto-generated weekly departmental report",
        disabled: false,
      },
      {
        value: "action_points_autogenerated" as ContentChoice,
        label: "Action Points",
        icon: ClipboardList,
        desc: "Auto-generated Action Points PDF from Action Tracker Management",
        disabled: false,
      },
      {
        value: "knowledge_sharing_session" as ContentChoice,
        label: "Knowledge Sharing Session",
        icon: FileText,
        desc: "Uses uploaded Knowledge Sharing Session file from Reports",
        disabled: !currentDocByType.knowledgeSharingSession,
        helperHref: "/admin/reports/kss",
        helperLabel: "Go to KSS",
      },
      {
        value: "minutes_of_meeting" as ContentChoice,
        label: "Minutes of Meeting",
        icon: FileText,
        desc: "Uses uploaded Minutes of Meeting PDF from Reports",
        disabled: !currentDocByType.minutesOfMeeting,
        helperHref: "/admin/reports/minutes-of-meeting",
        helperLabel: "Go to Minutes",
      },
    ],
    [currentDocByType.knowledgeSharingSession, currentDocByType.minutesOfMeeting]
  )

  // ── Computed ────────────────────────────────────────────────────────────────
  const filteredEmployees = useMemo(() => {
    if (!searchQuery.trim()) return employees
    const q = searchQuery.toLowerCase()
    return employees.filter(
      (e) =>
        e.full_name?.toLowerCase().includes(q) ||
        e.company_email?.toLowerCase().includes(q) ||
        e.additional_email?.toLowerCase().includes(q) ||
        e.department?.toLowerCase().includes(q)
    )
  }, [employees, searchQuery])

  // Parse the delivered-emails textarea into a normalised Set for resend_missed mode
  const deliveredEmailSet = useMemo(() => {
    return new Set(
      deliveredEmailsText
        .split(/[\n,]+/)
        .map((e) => e.trim().toLowerCase())
        .filter(Boolean)
    )
  }, [deliveredEmailsText])

  // Emails that are in the employee list but NOT in the delivered set
  const missedRecipients = useMemo(() => {
    if (recipientMode !== "resend_missed" || deliveredEmailSet.size === 0) return []
    const missed: string[] = []
    employees.forEach((e) => {
      const ce = e.company_email?.toLowerCase()
      const ae = e.additional_email?.toLowerCase()
      if (ce && !deliveredEmailSet.has(ce)) missed.push(ce)
      if (ae && !deliveredEmailSet.has(ae)) missed.push(ae)
    })
    return missed
  }, [recipientMode, employees, deliveredEmailSet])

  const resolvedRecipients = useMemo(() => {
    const emailSet = new Set<string>()
    if (recipientMode === "all" || recipientMode === "all_plus") {
      employees.forEach((e) => {
        if (e.company_email) emailSet.add(e.company_email.toLowerCase())
        if (e.additional_email) emailSet.add(e.additional_email.toLowerCase())
      })
    } else if (recipientMode === "select") {
      employees.forEach((e) => {
        if (selectedEmployeeIds.has(e.id)) {
          if (e.company_email) emailSet.add(e.company_email.toLowerCase())
          if (e.additional_email) emailSet.add(e.additional_email.toLowerCase())
        }
      })
    } else if (recipientMode === "resend_missed") {
      missedRecipients.forEach((email) => emailSet.add(email))
    }
    if (recipientMode === "manual" || recipientMode === "all_plus") {
      manualEmails.forEach((m) => {
        emailSet.add(m.toLowerCase())
      })
    }
    return Array.from(emailSet)
  }, [recipientMode, employees, selectedEmployeeIds, manualEmails, missedRecipients])

  const adminHrPreparers = useMemo(() => {
    return employees
      .filter((e) => {
        const dept = (e.department || "").toLowerCase()
        return dept.includes("admin") && dept.includes("hr")
      })
      .map((e) => e.full_name)
      .filter(Boolean)
      .sort((a, b) => a.localeCompare(b))
  }, [employees])

  useEffect(() => {
    if (adminHrPreparers.length === 0) {
      setSelectedPreparedBy("Terna")
      return
    }

    const currentDept = (currentUser?.department || "").toLowerCase()
    const currentName = (currentUser?.full_name || "").trim()
    const isCurrentUserAdminHr = currentDept.includes("admin") && currentDept.includes("hr")
    const ternaName = adminHrPreparers.find((name) => name.trim().toLowerCase().includes("terna"))

    const preferredName =
      ternaName ||
      (isCurrentUserAdminHr && currentName && adminHrPreparers.includes(currentName)
        ? currentName
        : adminHrPreparers[0])

    if (!hasAppliedDefaultPreparer.current) {
      setSelectedPreparedBy(preferredName)
      hasAppliedDefaultPreparer.current = true
      return
    }

    if (!selectedPreparedBy || !adminHrPreparers.includes(selectedPreparedBy)) {
      setSelectedPreparedBy(preferredName)
    }
  }, [adminHrPreparers, currentUser?.department, currentUser?.full_name, selectedPreparedBy])

  // ── Handlers ────────────────────────────────────────────────────────────────
  const toggleEmployee = useCallback((id: string) => {
    setSelectedEmployeeIds((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }, [])

  const selectAll = useCallback(() => {
    setSelectedEmployeeIds(new Set(employees.map((e) => e.id)))
  }, [employees])

  const deselectAll = useCallback(() => {
    setSelectedEmployeeIds(new Set())
  }, [])

  const addManualEmail = useCallback(() => {
    const email = manualInput.trim().toLowerCase()
    if (!email) return
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      toast.error("Invalid email address")
      return
    }
    if (manualEmails.includes(email)) {
      toast.error("Email already added")
      return
    }
    setManualEmails((prev) => [...prev, email])
    setManualInput("")
  }, [manualInput, manualEmails])

  const removeManualEmail = useCallback((email: string) => {
    setManualEmails((prev) => prev.filter((e) => e !== email))
  }, [])

  const toggleContentChoice = useCallback(
    (choice: ContentChoice, disabled?: boolean) => {
      if (disabled) return
      setSelectedContentChoices((prev) => {
        const next = new Set(prev)
        if (next.has(choice)) next.delete(choice)
        else next.add(choice)
        return next
      })
    },
    [setSelectedContentChoices]
  )

  // ── Week options (must be defined before handlers that reference it) ─────────
  const weekOptions = useMemo(() => Array.from({ length: 52 }, (_, i) => i + 1), [])

  const toggleWeek = useCallback((w: number) => {
    setSelectedWeeks((prev) => {
      const next = new Set(prev)
      if (next.has(w)) next.delete(w)
      else next.add(w)
      return next
    })
  }, [])

  const selectAllWeeks = useCallback(() => {
    setSelectedWeeks(new Set(weekOptions))
  }, [weekOptions])

  const deselectAllWeeks = useCallback(() => {
    setSelectedWeeks(new Set())
  }, [])

  const { isSending, sendResult, handleSend, deactivateSchedule } = useWeeklySummarySend({
    resolvedRecipients,
    selectedContentChoices,
    allKssDocs,
    allMinutesDocs,
    sendTiming,
    scheduledDate,
    scheduledTime,
    recurringDay,
    recurringTime,
    selectedWeeks,
    yearNumber,
    selectedPreparedBy,
    currentUser,
    fetchSchedules,
  })

  // ── Render ──────────────────────────────────────────────────────────────────
  const yearOptions = [currentYear - 1, currentYear, currentYear + 1]

  return (
    <PageWrapper maxWidth="full" background="gradient">
      <PageHeader
        title="Weekly Summary Mailings"
        description="Send selected weekly meeting documents to selected recipients."
        icon={Mail}
        backLink={{ href: "/admin/reports", label: "Back to Reports" }}
      />

      <div className="grid items-start gap-6 lg:grid-cols-3">
        {/* ── LEFT: Settings ────────────────────────────────────────────── */}
        <div className="space-y-6 lg:col-span-2">
          <WeeklySummaryForm
            selectedWeeks={selectedWeeks}
            yearNumber={yearNumber}
            toggleWeek={toggleWeek}
            selectAllWeeks={selectAllWeeks}
            deselectAllWeeks={deselectAllWeeks}
            setYearNumber={setYearNumber}
            weekOptions={weekOptions}
            yearOptions={yearOptions}
            currentWeekNumber={currentWeekNumber}
            contentOptions={contentOptions}
            selectedContentChoices={selectedContentChoices}
            toggleContentChoice={toggleContentChoice}
            adminHrPreparers={adminHrPreparers}
            selectedPreparedBy={selectedPreparedBy}
            setSelectedPreparedBy={setSelectedPreparedBy}
          />

          <RecipientSelector
            employees={employees}
            filteredEmployees={filteredEmployees}
            recipientMode={recipientMode}
            setRecipientMode={setRecipientMode}
            selectedEmployeeIds={selectedEmployeeIds}
            toggleEmployee={toggleEmployee}
            selectAll={selectAll}
            deselectAll={deselectAll}
            searchQuery={searchQuery}
            setSearchQuery={setSearchQuery}
            manualEmails={manualEmails}
            manualInput={manualInput}
            setManualInput={setManualInput}
            addManualEmail={addManualEmail}
            removeManualEmail={removeManualEmail}
            deliveredEmailsText={deliveredEmailsText}
            setDeliveredEmailsText={setDeliveredEmailsText}
            missedRecipients={missedRecipients}
          />

          <SchedulingOptions
            sendTiming={sendTiming}
            setSendTiming={setSendTiming}
            scheduledDate={scheduledDate}
            setScheduledDate={setScheduledDate}
            scheduledTime={scheduledTime}
            setScheduledTime={setScheduledTime}
            recurringDay={recurringDay}
            setRecurringDay={setRecurringDay}
            recurringTime={recurringTime}
            setRecurringTime={setRecurringTime}
            activeSchedules={activeSchedules}
            deactivateSchedule={deactivateSchedule}
          />
        </div>

        {/* ── RIGHT: Summary & Send ─────────────────────────────────────── */}
        <aside className="space-y-6 lg:sticky lg:top-[120px] lg:max-h-[calc(100vh-136px)] lg:self-start lg:overflow-y-auto lg:pr-1">
          <SummarySidebarCard
            selectedWeeks={selectedWeeks}
            yearNumber={yearNumber}
            selectedContentChoices={selectedContentChoices}
            allKssDocs={allKssDocs}
            allMinutesDocs={allMinutesDocs}
            autogeneratedActionPointsName={autogeneratedActionPointsName}
            resolvedRecipients={resolvedRecipients}
            sendTiming={sendTiming}
            recurringDay={recurringDay}
            recurringTime={recurringTime}
            scheduledDate={scheduledDate}
            scheduledTime={scheduledTime}
            isSending={isSending}
            onSend={handleSend}
          />
          {sendResult?.results && <SendResultPanel results={sendResult.results} />}
        </aside>
      </div>
    </PageWrapper>
  )
}
