"use client"

import { useState, useMemo, useCallback, useEffect, useRef } from "react"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { PageWrapper, PageHeader } from "@/components/layout"
import { Mail, FileText, ClipboardList } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { getCurrentOfficeWeek } from "@/lib/meeting-week"
import { QUERY_KEYS } from "@/lib/query-keys"
import { toast } from "sonner"
import { RecipientSelector } from "./_components/RecipientSelector"
import { WeeklySummaryForm } from "./_components/WeeklySummaryForm"
import { SchedulingOptions } from "./_components/SchedulingOptions"
import { SendResultPanel } from "./_components/SendResultPanel"
import { SummarySidebarCard } from "./_components/SummarySidebarCard"
import { useWeeklySummarySend } from "./_components/use-weekly-summary-send"

type Employee = {
  id: string
  full_name: string
  company_email: string | null
  additional_email: string | null
  department: string | null
  employment_status: string | null
}

type RecipientMode = "all" | "select" | "manual" | "all_plus"
type ContentChoice =
  | "weekly_report"
  | "action_points_autogenerated"
  | "knowledge_sharing_session"
  | "minutes_of_meeting"
  | "action_points_manual"
type SendTiming = "now" | "scheduled" | "recurring"

type MeetingWeekDocument = {
  id: string
  meeting_week: number
  meeting_year: number
  document_type: "knowledge_sharing_session" | "minutes" | "action_points"
  department: string | null
  presenter_id: string | null
  file_name: string
  version_no: number
  is_current: boolean
  signed_url: string | null
  created_at: string
}

type MailDocRef = {
  id: string
  file_name: string
  display_name: string
}

function sanitizeAttachmentToken(value: string): string {
  return (
    String(value || "Unknown")
      .trim()
      .replace(/\s+/g, "_")
      .replace(/[^a-zA-Z0-9_-]/g, "_")
      .replace(/_+/g, "_")
      .replace(/^_+|_+$/g, "") || "Unknown"
  )
}

function getFileExtension(fileName: string): string {
  const lower = String(fileName || "").toLowerCase()
  if (lower.endsWith(".pdf")) return "pdf"
  if (lower.endsWith(".docx")) return "docx"
  if (lower.endsWith(".pptx")) return "pptx"
  return "pdf"
}

function buildMeetingDocumentDisplayName(document: MeetingWeekDocument, presenterName?: string | null): string {
  const extension = getFileExtension(document.file_name)

  if (document.document_type === "knowledge_sharing_session") {
    return `KSS_${sanitizeAttachmentToken(document.department || "Unknown")}_${sanitizeAttachmentToken(
      presenterName || "Unknown"
    )}_Week_${document.meeting_week}_${document.meeting_year}.${extension}`
  }

  if (document.document_type === "minutes") {
    return `Minutes_of_Meeting_Week_${document.meeting_week}_${document.meeting_year}.${extension}`
  }

  return `Action_Points_Manual_Week_${document.meeting_week}_${document.meeting_year}.${extension}`
}

interface Props {
  employees: Employee[]
  currentUser?: {
    id: string
    full_name: string | null
    department: string | null
  }
}

export function WeeklySummaryContent({ employees, currentUser }: Props) {
  const supabase = createClient()
  const currentOfficeWeek = getCurrentOfficeWeek()

  // ── State ──────────────────────────────────────────────────────────────────
  const [recipientMode, setRecipientMode] = useState<RecipientMode>("select")
  const [selectedEmployeeIds, setSelectedEmployeeIds] = useState<Set<string>>(new Set())
  const [manualEmails, setManualEmails] = useState<string[]>([])
  const [manualInput, setManualInput] = useState("")
  const [searchQuery, setSearchQuery] = useState("")

  const [selectedContentChoices, setSelectedContentChoices] = useState<Set<ContentChoice>>(
    new Set<ContentChoice>(["weekly_report"])
  )
  const [selectedPreparedBy, setSelectedPreparedBy] = useState("Terna")

  const currentYear = currentOfficeWeek.year
  const currentWeekNumber = currentOfficeWeek.week
  const [weekNumber, setWeekNumber] = useState(currentWeekNumber)
  const [yearNumber, setYearNumber] = useState(currentYear)

  const [sendTiming, setSendTiming] = useState<SendTiming>("now")
  const [scheduledDate, setScheduledDate] = useState("")
  const [scheduledTime, setScheduledTime] = useState("09:00")
  const [recurringDay, setRecurringDay] = useState("monday")
  const [recurringTime, setRecurringTime] = useState("09:00")
  const hasAppliedDefaultPreparer = useRef(false)

  const queryClient = useQueryClient()

  // ── Fetch active schedules ──────────────────────────────────────────────────
  const { data: activeSchedules = [] } = useQuery({
    queryKey: QUERY_KEYS.adminWeeklySummaryMail(),
    queryFn: async () => {
      const { data, error } = await supabase
        .from("weekly_report_schedules")
        .select("*")
        .eq("is_active", true)
        .order("created_at", { ascending: false })
      if (error) {
        if (error.code === "42P01") return []
        throw new Error(error.message)
      }
      return data || []
    },
  })

  const fetchSchedules = useCallback(() => {
    queryClient.invalidateQueries({ queryKey: QUERY_KEYS.adminWeeklySummaryMail() })
  }, [queryClient])

  const { data: meetingDocuments = [] } = useQuery({
    queryKey: ["meeting-week-documents", weekNumber, yearNumber],
    queryFn: async (): Promise<MeetingWeekDocument[]> => {
      const res = await fetch(
        `/api/reports/meeting-week-documents?week=${weekNumber}&year=${yearNumber}&currentOnly=true`
      )
      const payload = await res.json()
      if (!res.ok) throw new Error(payload.error || "Failed to fetch meeting documents")
      return payload.data || []
    },
  })

  const currentDocByType = useMemo(() => {
    const toMailDocRef = (document: MeetingWeekDocument | undefined | null): MailDocRef | null => {
      if (!document) return null
      const presenterName =
        document.presenter_id && document.document_type === "knowledge_sharing_session"
          ? employees.find((employee) => employee.id === document.presenter_id)?.full_name || null
          : null

      return {
        id: document.id,
        file_name: document.file_name,
        display_name: buildMeetingDocumentDisplayName(document, presenterName),
      }
    }

    return {
      knowledgeSharingSession: toMailDocRef(
        meetingDocuments.find((d) => d.document_type === "knowledge_sharing_session" && d.is_current)
      ),
      minutesOfMeeting: toMailDocRef(meetingDocuments.find((d) => d.document_type === "minutes" && d.is_current)),
      actionPointsManual: toMailDocRef(
        meetingDocuments.find((d) => d.document_type === "action_points" && d.is_current)
      ),
    }
  }, [employees, meetingDocuments])

  const contentOptions = useMemo(
    () => [
      {
        value: "weekly_report" as ContentChoice,
        label: "Weekly Report",
        icon: FileText,
        desc: "Auto-generated weekly departmental report",
        disabled: false,
      },
      {
        value: "action_points_autogenerated" as ContentChoice,
        label: "Action Points (Autogenerated)",
        icon: ClipboardList,
        desc: "Auto-generated action tracker report",
        disabled: false,
      },
      {
        value: "knowledge_sharing_session" as ContentChoice,
        label: "Knowledge Sharing Session",
        icon: FileText,
        desc: "Uses uploaded Knowledge Sharing Session file from Reports",
        disabled: !currentDocByType.knowledgeSharingSession,
        helperHref: "/admin/reports/kss",
        helperLabel: "Go to KSS",
      },
      {
        value: "minutes_of_meeting" as ContentChoice,
        label: "Minutes of Meeting",
        icon: FileText,
        desc: "Uses uploaded Minutes of Meeting PDF from Reports",
        disabled: !currentDocByType.minutesOfMeeting,
        helperHref: "/admin/reports/minutes-of-meeting",
        helperLabel: "Go to Minutes",
      },
      {
        value: "action_points_manual" as ContentChoice,
        label: "Action Points (Manual)",
        icon: ClipboardList,
        desc: "Uses uploaded manual Action Points PDF from Reports",
        disabled: !currentDocByType.actionPointsManual,
        helperHref: "/admin/reports/action-points-manual",
        helperLabel: "Go to Action Points",
      },
    ],
    [currentDocByType.actionPointsManual, currentDocByType.knowledgeSharingSession, currentDocByType.minutesOfMeeting]
  )

  // ── Computed ────────────────────────────────────────────────────────────────
  const filteredEmployees = useMemo(() => {
    if (!searchQuery.trim()) return employees
    const q = searchQuery.toLowerCase()
    return employees.filter(
      (e) =>
        e.full_name?.toLowerCase().includes(q) ||
        e.company_email?.toLowerCase().includes(q) ||
        e.additional_email?.toLowerCase().includes(q) ||
        e.department?.toLowerCase().includes(q)
    )
  }, [employees, searchQuery])

  const resolvedRecipients = useMemo(() => {
    const emailSet = new Set<string>()
    if (recipientMode === "all" || recipientMode === "all_plus") {
      employees.forEach((e) => {
        if (e.company_email) emailSet.add(e.company_email.toLowerCase())
        if (e.additional_email) emailSet.add(e.additional_email.toLowerCase())
      })
    } else if (recipientMode === "select") {
      employees.forEach((e) => {
        if (selectedEmployeeIds.has(e.id)) {
          if (e.company_email) emailSet.add(e.company_email.toLowerCase())
          if (e.additional_email) emailSet.add(e.additional_email.toLowerCase())
        }
      })
    }
    if (recipientMode === "manual" || recipientMode === "all_plus") {
      manualEmails.forEach((m) => {
        emailSet.add(m.toLowerCase())
      })
    }
    return Array.from(emailSet)
  }, [recipientMode, employees, selectedEmployeeIds, manualEmails])

  const adminHrPreparers = useMemo(() => {
    return employees
      .filter((e) => {
        const dept = (e.department || "").toLowerCase()
        return dept.includes("admin") && dept.includes("hr")
      })
      .map((e) => e.full_name)
      .filter(Boolean)
      .sort((a, b) => a.localeCompare(b))
  }, [employees])

  useEffect(() => {
    if (adminHrPreparers.length === 0) {
      setSelectedPreparedBy("Terna")
      return
    }

    const currentDept = (currentUser?.department || "").toLowerCase()
    const currentName = (currentUser?.full_name || "").trim()
    const isCurrentUserAdminHr = currentDept.includes("admin") && currentDept.includes("hr")
    const ternaName = adminHrPreparers.find((name) => name.trim().toLowerCase().includes("terna"))

    const preferredName =
      ternaName ||
      (isCurrentUserAdminHr && currentName && adminHrPreparers.includes(currentName)
        ? currentName
        : adminHrPreparers[0])

    if (!hasAppliedDefaultPreparer.current) {
      setSelectedPreparedBy(preferredName)
      hasAppliedDefaultPreparer.current = true
      return
    }

    if (!selectedPreparedBy || !adminHrPreparers.includes(selectedPreparedBy)) {
      setSelectedPreparedBy(preferredName)
    }
  }, [adminHrPreparers, currentUser?.department, currentUser?.full_name, selectedPreparedBy])

  // ── Handlers ────────────────────────────────────────────────────────────────
  const toggleEmployee = useCallback((id: string) => {
    setSelectedEmployeeIds((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }, [])

  const selectAll = useCallback(() => {
    setSelectedEmployeeIds(new Set(employees.map((e) => e.id)))
  }, [employees])

  const deselectAll = useCallback(() => {
    setSelectedEmployeeIds(new Set())
  }, [])

  const addManualEmail = useCallback(() => {
    const email = manualInput.trim().toLowerCase()
    if (!email) return
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      toast.error("Invalid email address")
      return
    }
    if (manualEmails.includes(email)) {
      toast.error("Email already added")
      return
    }
    setManualEmails((prev) => [...prev, email])
    setManualInput("")
  }, [manualInput, manualEmails])

  const removeManualEmail = useCallback((email: string) => {
    setManualEmails((prev) => prev.filter((e) => e !== email))
  }, [])

  const toggleContentChoice = useCallback(
    (choice: ContentChoice, disabled?: boolean) => {
      if (disabled) return
      setSelectedContentChoices((prev) => {
        const next = new Set(prev)
        if (next.has(choice)) next.delete(choice)
        else next.add(choice)
        return next
      })
    },
    [setSelectedContentChoices]
  )

  const { isSending, sendResult, handleSend, deactivateSchedule } = useWeeklySummarySend({
    resolvedRecipients,
    selectedContentChoices,
    currentDocByType,
    sendTiming,
    scheduledDate,
    scheduledTime,
    recurringDay,
    recurringTime,
    weekNumber,
    yearNumber,
    selectedPreparedBy,
    currentUser,
    fetchSchedules,
  })

  // ── Render ──────────────────────────────────────────────────────────────────
  const weekOptions = Array.from({ length: 52 }, (_, i) => i + 1)
  const yearOptions = [currentYear - 1, currentYear, currentYear + 1]

  return (
    <PageWrapper maxWidth="full" background="gradient">
      <PageHeader
        title="Weekly Summary Mailings"
        description="Send selected weekly meeting documents to selected recipients."
        icon={Mail}
        backLink={{ href: "/admin/reports", label: "Back to Reports" }}
      />

      <div className="grid items-start gap-6 lg:grid-cols-3">
        {/* ── LEFT: Settings ────────────────────────────────────────────── */}
        <div className="space-y-6 lg:col-span-2">
          <WeeklySummaryForm
            weekNumber={weekNumber}
            yearNumber={yearNumber}
            setWeekNumber={setWeekNumber}
            setYearNumber={setYearNumber}
            weekOptions={weekOptions}
            yearOptions={yearOptions}
            contentOptions={contentOptions}
            selectedContentChoices={selectedContentChoices}
            toggleContentChoice={toggleContentChoice}
            adminHrPreparers={adminHrPreparers}
            selectedPreparedBy={selectedPreparedBy}
            setSelectedPreparedBy={setSelectedPreparedBy}
          />

          <RecipientSelector
            employees={employees}
            filteredEmployees={filteredEmployees}
            recipientMode={recipientMode}
            setRecipientMode={setRecipientMode}
            selectedEmployeeIds={selectedEmployeeIds}
            toggleEmployee={toggleEmployee}
            selectAll={selectAll}
            deselectAll={deselectAll}
            searchQuery={searchQuery}
            setSearchQuery={setSearchQuery}
            manualEmails={manualEmails}
            manualInput={manualInput}
            setManualInput={setManualInput}
            addManualEmail={addManualEmail}
            removeManualEmail={removeManualEmail}
          />

          <SchedulingOptions
            sendTiming={sendTiming}
            setSendTiming={setSendTiming}
            scheduledDate={scheduledDate}
            setScheduledDate={setScheduledDate}
            scheduledTime={scheduledTime}
            setScheduledTime={setScheduledTime}
            recurringDay={recurringDay}
            setRecurringDay={setRecurringDay}
            recurringTime={recurringTime}
            setRecurringTime={setRecurringTime}
            activeSchedules={activeSchedules}
            deactivateSchedule={deactivateSchedule}
          />
        </div>

        {/* ── RIGHT: Summary & Send ─────────────────────────────────────── */}
        <aside className="space-y-6 lg:sticky lg:top-[120px] lg:max-h-[calc(100vh-136px)] lg:self-start lg:overflow-y-auto lg:pr-1">
          <SummarySidebarCard
            weekNumber={weekNumber}
            yearNumber={yearNumber}
            selectedContentChoices={selectedContentChoices}
            currentDocByType={currentDocByType}
            resolvedRecipients={resolvedRecipients}
            sendTiming={sendTiming}
            recurringDay={recurringDay}
            recurringTime={recurringTime}
            scheduledDate={scheduledDate}
            scheduledTime={scheduledTime}
            isSending={isSending}
            onSend={handleSend}
          />
          {sendResult?.results && <SendResultPanel results={sendResult.results} />}
        </aside>
      </div>
    </PageWrapper>
  )
}
