"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Send, Clock, Users, FileText, ClipboardList, Loader2, AlertCircle, Repeat } from "lucide-react"

type ContentChoice =
  | "weekly_report"
  | "action_points_autogenerated"
  | "knowledge_sharing_session"
  | "minutes_of_meeting"

type SendTiming = "now" | "scheduled" | "recurring"

interface DocRef {
  file_name: string
  display_name: string
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

interface SummarySidebarCardProps {
  selectedWeeks: Set<number>
  yearNumber: number
  selectedContentChoices: Set<ContentChoice>
  autogeneratedWeeklyReportName: string
  allKssDocs: DocRef[]
  allMinutesDocs: DocRef[]
  autogeneratedActionPointsName: string
  resolvedRecipients: string[]
  sendTiming: SendTiming
  recurringDay: string
  recurringTime: string
  scheduledDate: string
  scheduledTime: string
  isSending: boolean
  onSend: () => void
}

export function SummarySidebarCard({
  selectedWeeks,
  yearNumber,
  selectedContentChoices,
  autogeneratedWeeklyReportName,
  allKssDocs,
  allMinutesDocs,
  autogeneratedActionPointsName,
  resolvedRecipients,
  sendTiming,
  recurringDay,
  recurringTime,
  scheduledDate,
  scheduledTime,
  isSending,
  onSend,
}: SummarySidebarCardProps) {
  const isDisabled =
    isSending ||
    selectedWeeks.size === 0 ||
    resolvedRecipients.length === 0 ||
    selectedContentChoices.size === 0 ||
    (selectedContentChoices.has("knowledge_sharing_session") && allKssDocs.length === 0) ||
    (selectedContentChoices.has("minutes_of_meeting") && allMinutesDocs.length === 0)

  const sortedWeeks = Array.from(selectedWeeks).sort((a, b) => a - b)

  return (
    <Card className="border-green-200 dark:border-green-900">
      <CardHeader className="pb-3">
        <CardTitle className="text-lg">Summary</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Week info */}
        <div className="space-y-2">
          <div className="flex items-start justify-between gap-2 text-sm">
            <span className="text-muted-foreground shrink-0">Week{sortedWeeks.length !== 1 ? "s" : ""}</span>
            {sortedWeeks.length === 0 ? (
              <Badge variant="outline" className="text-muted-foreground">
                None
              </Badge>
            ) : sortedWeeks.length <= 5 ? (
              <div className="flex flex-wrap justify-end gap-1">
                {sortedWeeks.map((w) => (
                  <Badge key={w}>
                    W{w}, {yearNumber}
                  </Badge>
                ))}
              </div>
            ) : (
              <Badge>
                {sortedWeeks.length} weeks &mdash; {yearNumber}
              </Badge>
            )}
          </div>
        </div>

        <div className="border-t" />

        {/* Content */}
        <div className="space-y-1">
          <div className="text-muted-foreground text-xs font-medium tracking-wider uppercase">Attachments</div>
          <div className="flex flex-wrap gap-1.5">
            {selectedContentChoices.has("weekly_report") && (
              <Badge variant="secondary" className="gap-1">
                <FileText className="h-3 w-3" /> {autogeneratedWeeklyReportName}
              </Badge>
            )}
            {selectedContentChoices.has("action_points_autogenerated") && (
              <Badge variant="secondary" className="gap-1">
                <ClipboardList className="h-3 w-3" /> {autogeneratedActionPointsName}
              </Badge>
            )}
            {selectedContentChoices.has("knowledge_sharing_session") &&
              allKssDocs.length > 0 &&
              allKssDocs.map((doc) => (
                <Badge key={doc.file_name} variant="secondary" className="gap-1">
                  <FileText className="h-3 w-3" /> {doc.display_name}
                </Badge>
              ))}
            {selectedContentChoices.has("knowledge_sharing_session") && allKssDocs.length === 0 && (
              <Badge variant="outline" className="text-muted-foreground gap-1">
                <FileText className="h-3 w-3" /> KSS — none uploaded for selected weeks
              </Badge>
            )}
            {selectedContentChoices.has("minutes_of_meeting") &&
              allMinutesDocs.length > 0 &&
              allMinutesDocs.map((doc) => (
                <Badge key={doc.file_name} variant="secondary" className="gap-1">
                  <FileText className="h-3 w-3" /> {doc.display_name}
                </Badge>
              ))}
            {selectedContentChoices.has("minutes_of_meeting") && allMinutesDocs.length === 0 && (
              <Badge variant="outline" className="text-muted-foreground gap-1">
                <FileText className="h-3 w-3" /> Minutes — none uploaded for selected weeks
              </Badge>
            )}
            {selectedContentChoices.size === 0 && (
              <Badge variant="outline" className="text-muted-foreground">
                None selected
              </Badge>
            )}
          </div>
        </div>

        <div className="border-t" />

        {/* Recipients */}
        <div className="space-y-1">
          <div className="text-muted-foreground text-xs font-medium tracking-wider uppercase">Recipients</div>
          <div className="flex items-center gap-2">
            <Users className="h-4 w-4 text-green-600" />
            <span className="text-2xl font-bold">{resolvedRecipients.length}</span>
            <span className="text-muted-foreground text-sm">email(s)</span>
          </div>
          {resolvedRecipients.length > 0 && (
            <div className="mt-2 max-h-[160px] space-y-0.5 overflow-y-auto rounded-md border p-2 text-xs">
              {resolvedRecipients.map((email) => (
                <div key={email} className="truncate">
                  {email}
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="border-t" />

        {/* Timing */}
        <div className="space-y-1">
          <div className="text-muted-foreground text-xs font-medium tracking-wider uppercase">Delivery</div>
          <div className="flex items-center gap-2 text-sm">
            {sendTiming === "now" ? (
              <>
                <Send className="h-4 w-4 text-green-600" />
                <span>Immediately</span>
              </>
            ) : sendTiming === "recurring" ? (
              <>
                <Repeat className="h-4 w-4 text-green-600" />
                <span>
                  Every {capitalize(recurringDay)} at {recurringTime}
                </span>
              </>
            ) : (
              <>
                <Clock className="h-4 w-4 text-orange-600" />
                <span>
                  {scheduledDate
                    ? new Date(`${scheduledDate}T${scheduledTime}`).toLocaleString("en-GB", {
                        weekday: "short",
                        day: "numeric",
                        month: "short",
                        hour: "2-digit",
                        minute: "2-digit",
                      })
                    : "Not set"}
                </span>
              </>
            )}
          </div>
        </div>

        <Button
          className="mt-4 w-full bg-green-600 text-white hover:bg-green-700"
          size="lg"
          disabled={isDisabled}
          onClick={onSend}
        >
          {isSending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Sending...
            </>
          ) : sendTiming === "scheduled" ? (
            <>
              <Clock className="mr-2 h-4 w-4" />
              Schedule Send
            </>
          ) : sendTiming === "recurring" ? (
            <>
              <Repeat className="mr-2 h-4 w-4" />
              Save Recurring
            </>
          ) : (
            <>
              <Send className="mr-2 h-4 w-4" />
              Send Now
            </>
          )}
        </Button>

        {selectedWeeks.size === 0 && (
          <p className="text-destructive text-center text-xs">
            <AlertCircle className="mr-1 inline h-3 w-3" />
            No weeks selected
          </p>
        )}
        {resolvedRecipients.length === 0 && (
          <p className="text-destructive text-center text-xs">
            <AlertCircle className="mr-1 inline h-3 w-3" />
            No recipients selected
          </p>
        )}
        {selectedContentChoices.size === 0 && (
          <p className="text-destructive text-center text-xs">
            <AlertCircle className="mr-1 inline h-3 w-3" />
            No content selected
          </p>
        )}
      </CardContent>
    </Card>
  )
}
