"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Send, Clock, Users, FileText, ClipboardList, Loader2, AlertCircle, Repeat } from "lucide-react"

type ContentChoice =
  | "weekly_report"
  | "action_points_autogenerated"
  | "knowledge_sharing_session"
  | "minutes_of_meeting"
  | "action_points_manual"

type SendTiming = "now" | "scheduled" | "recurring"

interface DocRef {
  file_name: string
}

interface CurrentDocByType {
  knowledgeSharingSession: DocRef | null
  minutesOfMeeting: DocRef | null
  actionPointsManual: DocRef | null
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

interface SummarySidebarCardProps {
  weekNumber: number
  yearNumber: number
  selectedContentChoices: Set<ContentChoice>
  currentDocByType: CurrentDocByType
  resolvedRecipients: string[]
  sendTiming: SendTiming
  recurringDay: string
  recurringTime: string
  scheduledDate: string
  scheduledTime: string
  isSending: boolean
  onSend: () => void
}

export function SummarySidebarCard({
  weekNumber,
  yearNumber,
  selectedContentChoices,
  currentDocByType,
  resolvedRecipients,
  sendTiming,
  recurringDay,
  recurringTime,
  scheduledDate,
  scheduledTime,
  isSending,
  onSend,
}: SummarySidebarCardProps) {
  const isDisabled =
    isSending ||
    resolvedRecipients.length === 0 ||
    selectedContentChoices.size === 0 ||
    (selectedContentChoices.has("knowledge_sharing_session") && !currentDocByType.knowledgeSharingSession) ||
    (selectedContentChoices.has("minutes_of_meeting") && !currentDocByType.minutesOfMeeting) ||
    (selectedContentChoices.has("action_points_manual") && !currentDocByType.actionPointsManual)

  return (
    <Card className="border-green-200 dark:border-green-900">
      <CardHeader className="pb-3">
        <CardTitle className="text-lg">Summary</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Week info */}
        <div className="space-y-2">
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Week</span>
            <Badge>
              W{weekNumber}, {yearNumber}
            </Badge>
          </div>
        </div>

        <div className="border-t" />

        {/* Content */}
        <div className="space-y-1">
          <div className="text-muted-foreground text-xs font-medium tracking-wider uppercase">Attachments</div>
          <div className="flex flex-wrap gap-1.5">
            {selectedContentChoices.has("weekly_report") && (
              <Badge variant="secondary" className="gap-1">
                <FileText className="h-3 w-3" /> Weekly Report
              </Badge>
            )}
            {selectedContentChoices.has("action_points_autogenerated") && (
              <Badge variant="secondary" className="gap-1">
                <ClipboardList className="h-3 w-3" /> Action Points (Autogenerated)
              </Badge>
            )}
            {selectedContentChoices.has("knowledge_sharing_session") && currentDocByType.knowledgeSharingSession && (
              <Badge variant="secondary" className="gap-1">
                <FileText className="h-3 w-3" /> {currentDocByType.knowledgeSharingSession.file_name}
              </Badge>
            )}
            {selectedContentChoices.has("minutes_of_meeting") && currentDocByType.minutesOfMeeting && (
              <Badge variant="secondary" className="gap-1">
                <FileText className="h-3 w-3" /> {currentDocByType.minutesOfMeeting.file_name}
              </Badge>
            )}
            {selectedContentChoices.has("action_points_manual") && currentDocByType.actionPointsManual && (
              <Badge variant="secondary" className="gap-1">
                <ClipboardList className="h-3 w-3" /> {currentDocByType.actionPointsManual.file_name}
              </Badge>
            )}
            {selectedContentChoices.size === 0 ? (
              <Badge variant="outline" className="text-muted-foreground">
                None selected
              </Badge>
            ) : null}
          </div>
        </div>

        <div className="border-t" />

        {/* Recipients */}
        <div className="space-y-1">
          <div className="text-muted-foreground text-xs font-medium tracking-wider uppercase">Recipients</div>
          <div className="flex items-center gap-2">
            <Users className="h-4 w-4 text-green-600" />
            <span className="text-2xl font-bold">{resolvedRecipients.length}</span>
            <span className="text-muted-foreground text-sm">email(s)</span>
          </div>
          {resolvedRecipients.length > 0 && (
            <div className="mt-2 max-h-[160px] space-y-0.5 overflow-y-auto rounded-md border p-2 text-xs">
              {resolvedRecipients.map((email) => (
                <div key={email} className="truncate">
                  {email}
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="border-t" />

        {/* Timing */}
        <div className="space-y-1">
          <div className="text-muted-foreground text-xs font-medium tracking-wider uppercase">Delivery</div>
          <div className="flex items-center gap-2 text-sm">
            {sendTiming === "now" ? (
              <>
                <Send className="h-4 w-4 text-green-600" />
                <span>Immediately</span>
              </>
            ) : sendTiming === "recurring" ? (
              <>
                <Repeat className="h-4 w-4 text-green-600" />
                <span>
                  Every {capitalize(recurringDay)} at {recurringTime}
                </span>
              </>
            ) : (
              <>
                <Clock className="h-4 w-4 text-orange-600" />
                <span>
                  {scheduledDate
                    ? new Date(`${scheduledDate}T${scheduledTime}`).toLocaleString("en-GB", {
                        weekday: "short",
                        day: "numeric",
                        month: "short",
                        hour: "2-digit",
                        minute: "2-digit",
                      })
                    : "Not set"}
                </span>
              </>
            )}
          </div>
        </div>

        <Button
          className="mt-4 w-full bg-green-600 text-white hover:bg-green-700"
          size="lg"
          disabled={isDisabled}
          onClick={onSend}
        >
          {isSending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Sending...
            </>
          ) : sendTiming === "scheduled" ? (
            <>
              <Clock className="mr-2 h-4 w-4" />
              Schedule Send
            </>
          ) : sendTiming === "recurring" ? (
            <>
              <Repeat className="mr-2 h-4 w-4" />
              Save Recurring
            </>
          ) : (
            <>
              <Send className="mr-2 h-4 w-4" />
              Send Now
            </>
          )}
        </Button>

        {resolvedRecipients.length === 0 && (
          <p className="text-destructive text-center text-xs">
            <AlertCircle className="mr-1 inline h-3 w-3" />
            No recipients selected
          </p>
        )}
        {selectedContentChoices.size === 0 && (
          <p className="text-destructive text-center text-xs">
            <AlertCircle className="mr-1 inline h-3 w-3" />
            No content selected
          </p>
        )}
      </CardContent>
    </Card>
  )
}
