"use client"

import { useState, useCallback } from "react"
import { toast } from "sonner"
import { createClient } from "@/lib/supabase/client"
import { writeAuditLogClient } from "@/lib/audit/client"
import { logger } from "@/lib/logger"

const log = logger("reports-mail-weekly-summary-send")

type ContentChoice =
  | "weekly_report"
  | "action_points_autogenerated"
  | "knowledge_sharing_session"
  | "minutes_of_meeting"
  | "action_points_manual"

type SendTiming = "now" | "scheduled" | "recurring"

interface DocRef {
  id: string
  file_name: string
}

interface CurrentDocByType {
  knowledgeSharingSession: DocRef | null
  minutesOfMeeting: DocRef | null
  actionPointsManual: DocRef | null
}

interface UseSendParams {
  resolvedRecipients: string[]
  selectedContentChoices: Set<ContentChoice>
  currentDocByType: CurrentDocByType
  sendTiming: SendTiming
  scheduledDate: string
  scheduledTime: string
  recurringDay: string
  recurringTime: string
  weekNumber: number
  yearNumber: number
  selectedPreparedBy: string
  currentUser?: { id?: string; department?: string | null; full_name?: string | null }
  fetchSchedules: () => void
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

export function useWeeklySummarySend({
  resolvedRecipients,
  selectedContentChoices,
  currentDocByType,
  sendTiming,
  scheduledDate,
  scheduledTime,
  recurringDay,
  recurringTime,
  weekNumber,
  yearNumber,
  selectedPreparedBy,
  currentUser,
  fetchSchedules,
}: UseSendParams) {
  const supabase = createClient()
  const [isSending, setIsSending] = useState(false)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [sendResult, setSendResult] = useState<any>(null)

  const logMailAudit = useCallback(
    async (params: { action: string; entityId: string; metadata?: Record<string, unknown> }) => {
      try {
        await writeAuditLogClient(
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          supabase as any,
          {
            action: "send",
            entityType: "mail_summary",
            entityId: params.entityId,
            metadata: { ...(params.metadata || {}), event: params.action },
            context: {
              actorId: currentUser?.id || undefined,
              department: currentUser?.department || "Admin & HR",
              source: "ui",
              route: "/admin/reports/weekly-summary",
            },
          },
          { failOpen: true }
        )
      } catch (error) {
        log.error("[weekly-report] Failed to write audit log", error)
      }
    },
    [currentUser?.department, currentUser?.id, supabase]
  )

  const doSend = useCallback(async () => {
    setIsSending(true)
    setSendResult(null)
    const toastId = toast.loading(`Sending weekly report to ${resolvedRecipients.length} recipient(s)...`)

    try {
      const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
      const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const payload: any = {
        recipients: resolvedRecipients,
        meetingWeek: weekNumber,
        meetingYear: yearNumber,
        preparedByName: selectedPreparedBy,
        requestedByUserId: currentUser?.id || null,
      }

      payload.skipWeeklyReport = !selectedContentChoices.has("weekly_report")
      payload.skipActionTracker = !selectedContentChoices.has("action_points_autogenerated")

      const additionalDocumentIds: string[] = []
      if (selectedContentChoices.has("knowledge_sharing_session") && currentDocByType.knowledgeSharingSession?.id) {
        additionalDocumentIds.push(currentDocByType.knowledgeSharingSession.id)
      }
      if (selectedContentChoices.has("minutes_of_meeting") && currentDocByType.minutesOfMeeting?.id) {
        additionalDocumentIds.push(currentDocByType.minutesOfMeeting.id)
      }
      if (selectedContentChoices.has("action_points_manual") && currentDocByType.actionPointsManual?.id) {
        additionalDocumentIds.push(currentDocByType.actionPointsManual.id)
      }
      if (additionalDocumentIds.length > 0) {
        payload.additionalDocumentIds = additionalDocumentIds
      }

      const res = await fetch(`${supabaseUrl}/functions/v1/send-weekly-report`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${supabaseKey}`,
        },
        body: JSON.stringify(payload),
      })

      const result = await res.json()
      if (!res.ok) throw new Error(result.error || "Failed to send weekly report")

      setSendResult(result)
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const successCount = result.results?.filter((r: any) => r.success).length || 0
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const failCount = result.results?.filter((r: any) => !r.success).length || 0

      if (failCount === 0) {
        toast.success(`✅ Weekly report sent to ${successCount} recipient(s)`, { id: toastId })
      } else {
        toast.warning(`Sent to ${successCount}, failed for ${failCount}`, { id: toastId })
      }

      await logMailAudit({
        action: "weekly_report_sent",
        entityId: crypto.randomUUID(),
        metadata: {
          meeting_week: weekNumber,
          meeting_year: yearNumber,
          content_choices: Array.from(selectedContentChoices),
          prepared_by: selectedPreparedBy,
          success_count: successCount,
          failure_count: failCount,
          recipient_count: resolvedRecipients.length,
        },
      })
    } catch (err: unknown) {
      log.error("[Weekly Report Error]", err)
      toast.error(err instanceof Error ? err.message : "Failed to send weekly report", { id: toastId })
    } finally {
      setIsSending(false)
    }
  }, [
    resolvedRecipients,
    weekNumber,
    yearNumber,
    selectedPreparedBy,
    selectedContentChoices,
    currentDocByType,
    currentUser?.id,
    logMailAudit,
  ])

  const handleSend = useCallback(async () => {
    if (resolvedRecipients.length === 0) {
      toast.error("No recipients selected")
      return
    }
    if (selectedContentChoices.size === 0) {
      toast.error("Select at least one content item")
      return
    }
    if (selectedContentChoices.has("knowledge_sharing_session") && !currentDocByType.knowledgeSharingSession) {
      toast.error("Knowledge Sharing Session file is not uploaded for this week")
      return
    }
    if (selectedContentChoices.has("minutes_of_meeting") && !currentDocByType.minutesOfMeeting) {
      toast.error("Minutes of Meeting file is not uploaded for this week")
      return
    }
    if (selectedContentChoices.has("action_points_manual") && !currentDocByType.actionPointsManual) {
      toast.error("Action Points (Manual) file is not uploaded for this week")
      return
    }
    if (
      sendTiming !== "now" &&
      (selectedContentChoices.has("knowledge_sharing_session") ||
        selectedContentChoices.has("minutes_of_meeting") ||
        selectedContentChoices.has("action_points_manual"))
    ) {
      toast.error("Stored file send options can only be sent immediately")
      return
    }

    // ── Scheduled ──────────────────────────────────────────────────────────
    if (sendTiming === "scheduled") {
      if (!scheduledDate) {
        toast.error("Please set a scheduled date")
        return
      }
      const scheduledDateTime = new Date(`${scheduledDate}T${scheduledTime}`)
      if (scheduledDateTime <= new Date()) {
        toast.error("Scheduled time must be in the future")
        return
      }

      const includeWeeklyReport = selectedContentChoices.has("weekly_report")
      const includeActionTracker = selectedContentChoices.has("action_points_autogenerated")

      let scheduleContentChoice: "weekly_report" | "action_tracker" | "both"
      if (includeWeeklyReport && includeActionTracker) {
        scheduleContentChoice = "both"
      } else if (includeWeeklyReport) {
        scheduleContentChoice = "weekly_report"
      } else if (includeActionTracker) {
        scheduleContentChoice = "action_tracker"
      } else {
        toast.error("Only Weekly Report and Action Points (Autogenerated) can be scheduled")
        return
      }

      const { error } = await supabase.from("weekly_report_schedules").insert({
        schedule_type: "one_time",
        meeting_week: weekNumber,
        meeting_year: yearNumber,
        recipients: resolvedRecipients,
        content_choice: scheduleContentChoice,
        next_run_at: scheduledDateTime.toISOString(),
      })

      if (error) {
        toast.error("Failed to save schedule: " + error.message)
        return
      }

      toast.success(
        `Email scheduled for ${scheduledDateTime.toLocaleString("en-GB", {
          weekday: "short",
          day: "numeric",
          month: "short",
          hour: "2-digit",
          minute: "2-digit",
        })}`
      )
      fetchSchedules()
      return
    }

    // ── Recurring ──────────────────────────────────────────────────────────
    if (sendTiming === "recurring") {
      const days = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
      const targetDay = days.indexOf(recurringDay)
      const now = new Date()
      const currentDay = now.getDay()
      let daysUntil = targetDay - currentDay
      const [h, m] = recurringTime.split(":")
      const targetMinutes = parseInt(h, 10) * 60 + parseInt(m, 10)
      const nowMinutes = now.getHours() * 60 + now.getMinutes()
      if (daysUntil < 0 || (daysUntil === 0 && nowMinutes >= targetMinutes)) daysUntil += 7
      const nextRun = new Date(now)
      nextRun.setDate(now.getDate() + daysUntil)
      nextRun.setHours(parseInt(h, 10), parseInt(m, 10), 0, 0)

      const includeWeeklyReport = selectedContentChoices.has("weekly_report")
      const includeActionTracker = selectedContentChoices.has("action_points_autogenerated")
      if (!includeWeeklyReport && !includeActionTracker) {
        toast.error("Recurring mode supports Weekly Report and Action Points (Autogenerated) only")
        return
      }

      const recurringContentChoice: "weekly_report" | "action_tracker" | "both" =
        includeWeeklyReport && includeActionTracker ? "both" : includeWeeklyReport ? "weekly_report" : "action_tracker"

      const { error } = await supabase.from("weekly_report_schedules").insert({
        schedule_type: "recurring",
        recipients: resolvedRecipients,
        content_choice: recurringContentChoice,
        send_day: recurringDay,
        send_time: recurringTime,
        next_run_at: nextRun.toISOString(),
      })

      if (error) {
        toast.error("Failed to save recurring schedule: " + error.message)
        return
      }

      toast.success(`Recurring weekly email set for every ${capitalize(recurringDay)} at ${recurringTime}`)
      fetchSchedules()
      return
    }

    // ── Immediate ──────────────────────────────────────────────────────────
    await doSend()
  }, [
    resolvedRecipients,
    selectedContentChoices,
    currentDocByType,
    sendTiming,
    scheduledDate,
    scheduledTime,
    recurringDay,
    recurringTime,
    weekNumber,
    yearNumber,
    supabase,
    fetchSchedules,
    doSend,
  ])

  const deactivateSchedule = useCallback(
    async (id: string) => {
      const { error } = await supabase.from("weekly_report_schedules").update({ is_active: false }).eq("id", id)
      if (error) {
        toast.error("Failed to deactivate schedule")
      } else {
        toast.success("Schedule deactivated")
        fetchSchedules()
      }
    },
    [supabase, fetchSchedules]
  )

  return { isSending, sendResult, handleSend, deactivateSchedule }
}
