"use client"

import { useState, useCallback } from "react"
import { toast } from "sonner"
import { createClient } from "@/lib/supabase/client"
import { writeAuditLogClient } from "@/lib/audit/client"
import { logger } from "@/lib/logger"

const log = logger("reports-mail-weekly-summary-send")

type ContentChoice =
  | "weekly_report"
  | "action_points_autogenerated"
  | "knowledge_sharing_session"
  | "minutes_of_meeting"

type SendTiming = "now" | "scheduled" | "recurring"

interface DocRef {
  id: string
  file_name: string
}

interface UseSendParams {
  resolvedRecipients: string[]
  selectedContentChoices: Set<ContentChoice>
  allKssDocs: DocRef[]
  allMinutesDocs: DocRef[]
  sendTiming: SendTiming
  scheduledDate: string
  scheduledTime: string
  recurringDay: string
  recurringTime: string
  selectedWeeks: Set<number>
  yearNumber: number
  selectedPreparedBy: string
  currentUser?: { id?: string; department?: string | null; full_name?: string | null }
  fetchSchedules: () => void
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function readFilenameFromDisposition(disposition: string | null, fallback: string) {
  if (!disposition) return fallback
  const utf8Match = disposition.match(/filename\*=UTF-8''([^;]+)/i)
  if (utf8Match?.[1]) {
    try {
      return decodeURIComponent(utf8Match[1])
    } catch {
      return utf8Match[1]
    }
  }

  const plainMatch = disposition.match(/filename="([^"]+)"/i) || disposition.match(/filename=([^;]+)/i)
  return plainMatch?.[1]?.trim() || fallback
}

async function toBase64FromBlob(blob: Blob): Promise<string> {
  const buffer = await blob.arrayBuffer()
  const bytes = new Uint8Array(buffer)
  let binary = ""
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i])
  return btoa(binary)
}

async function fetchActionPointsAttachment(params: {
  actions: unknown[]
  week: number
  year: number
  meetingDate?: string
}): Promise<{ blob: Blob; filename: string }> {
  const response = await fetch("/api/reports/action-points-export", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      format: "pdf",
      actions: params.actions,
      week: params.week,
      year: params.year,
      meetingDate: params.meetingDate,
    }),
  })

  if (!response.ok) {
    const detail = await response.text().catch(() => "")
    throw new Error(detail || "Failed to generate Action Points PDF")
  }

  const exportBlob = await response.blob()
  return {
    blob: exportBlob,
    filename: readFilenameFromDisposition(
      response.headers.get("Content-Disposition"),
      `ACOB Action Tracker - Week ${params.week}.pdf`
    ),
  }
}

export function useWeeklySummarySend({
  resolvedRecipients,
  selectedContentChoices,
  allKssDocs,
  allMinutesDocs,
  sendTiming,
  scheduledDate,
  scheduledTime,
  recurringDay,
  recurringTime,
  selectedWeeks,
  yearNumber,
  selectedPreparedBy,
  currentUser,
  fetchSchedules,
}: UseSendParams) {
  // Sorted array of selected weeks for iteration
  const weekNumbers = Array.from(selectedWeeks).sort((a, b) => a - b)
  const supabase = createClient()
  const [isSending, setIsSending] = useState(false)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [sendResult, setSendResult] = useState<any>(null)

  const logMailAudit = useCallback(
    async (params: { action: string; entityId: string; metadata?: Record<string, unknown> }) => {
      try {
        await writeAuditLogClient(
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          supabase as any,
          {
            action: "send",
            entityType: "mail_summary",
            entityId: params.entityId,
            metadata: { ...(params.metadata || {}), event: params.action },
            context: {
              actorId: currentUser?.id || undefined,
              department: currentUser?.department || "Admin & HR",
              source: "ui",
              route: "/admin/reports/weekly-summary",
            },
          },
          { failOpen: true }
        )
      } catch (error) {
        log.error("[weekly-report] Failed to write audit log", error)
      }
    },
    [currentUser?.department, currentUser?.id, supabase]
  )

  const doSend = useCallback(async () => {
    setIsSending(true)
    setSendResult(null)

    const weekLabel = weekNumbers.length === 1 ? `Week ${weekNumbers[0]}` : `${weekNumbers.length} weeks`

    const toastId = toast.loading(`Sending ${weekLabel} to ${resolvedRecipients.length} recipient(s)...`)

    try {
      const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
      const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

      // ── Build per-week action points attachments ────────────────────────────
      const actionTrackerAttachments: Array<{ base64: string; filename: string; week: number }> = []

      if (selectedContentChoices.has("action_points_autogenerated")) {
        for (const weekNum of weekNumbers) {
          const { data: actions, error: actionsError } = await supabase
            .from("action_items")
            .select("id, title, department, status, week_number, year")
            .eq("week_number", weekNum)
            .eq("year", yearNumber)

          if (actionsError) {
            throw new Error(actionsError.message || `Failed to load action items for Week ${weekNum}`)
          }

          const { data: meetingDate, error: meetingDateError } = await supabase.rpc(
            "weekly_report_effective_meeting_date",
            { p_week: weekNum, p_year: yearNumber }
          )

          if (meetingDateError) {
            throw new Error(meetingDateError.message || `Failed to resolve meeting date for Week ${weekNum}`)
          }

          const exportFile = await fetchActionPointsAttachment({
            actions: actions || [],
            week: weekNum,
            year: yearNumber,
            meetingDate: meetingDate ? String(meetingDate) : undefined,
          })

          actionTrackerAttachments.push({
            base64: await toBase64FromBlob(exportFile.blob),
            filename: exportFile.filename,
            week: weekNum,
          })
        }
      }

      // ── Build payload ───────────────────────────────────────────────────────
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const payload: any = {
        recipients: resolvedRecipients,
        // Pass all selected weeks; backend will include one report per week
        meetingWeeks: weekNumbers,
        meetingYear: yearNumber,
        // Legacy single-week field kept for backward-compat if only one week
        meetingWeek: weekNumbers[0],
        preparedByName: selectedPreparedBy,
        requestedByUserId: currentUser?.id || null,
        skipWeeklyReport: !selectedContentChoices.has("weekly_report"),
        skipActionTracker: !selectedContentChoices.has("action_points_autogenerated"),
      }

      // Collect IDs from ALL selected weeks' KSS and Minutes docs
      const additionalDocumentIds: string[] = []
      if (selectedContentChoices.has("knowledge_sharing_session")) {
        allKssDocs.forEach((d) => {
          if (d.id) additionalDocumentIds.push(d.id)
        })
      }
      if (selectedContentChoices.has("minutes_of_meeting")) {
        allMinutesDocs.forEach((d) => {
          if (d.id) additionalDocumentIds.push(d.id)
        })
      }
      if (additionalDocumentIds.length > 0) {
        payload.additionalDocumentIds = additionalDocumentIds
      }

      if (actionTrackerAttachments.length > 0) {
        // Multi-week: send array; single-week: keep legacy fields too
        payload.actionTrackerAttachments = actionTrackerAttachments
        payload.actionTrackerBase64 = actionTrackerAttachments[0].base64
        payload.actionTrackerFilename = actionTrackerAttachments[0].filename
      }

      const res = await fetch(`${supabaseUrl}/functions/v1/send-weekly-report`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${supabaseKey}`,
        },
        body: JSON.stringify(payload),
      })

      const result = await res.json()
      if (!res.ok) throw new Error(result.error || "Failed to send weekly report")

      setSendResult(result)
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const successCount = result.results?.filter((r: any) => r.success).length || 0
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const failCount = result.results?.filter((r: any) => !r.success).length || 0

      if (failCount === 0) {
        toast.success(`✅ ${weekLabel} sent to ${successCount} recipient(s)`, { id: toastId })
      } else {
        toast.warning(`Sent to ${successCount}, failed for ${failCount}`, { id: toastId })
      }

      await logMailAudit({
        action: "weekly_report_sent",
        entityId: crypto.randomUUID(),
        metadata: {
          meeting_weeks: weekNumbers,
          meeting_year: yearNumber,
          content_choices: Array.from(selectedContentChoices),
          prepared_by: selectedPreparedBy,
          success_count: successCount,
          failure_count: failCount,
          recipient_count: resolvedRecipients.length,
        },
      })
    } catch (err: unknown) {
      log.error("[Weekly Report Error]", err)
      toast.error(err instanceof Error ? err.message : "Failed to send weekly report", { id: toastId })
    } finally {
      setIsSending(false)
    }
  }, [
    resolvedRecipients,
    weekNumbers,
    yearNumber,
    selectedPreparedBy,
    selectedContentChoices,
    allKssDocs,
    allMinutesDocs,
    currentUser?.id,
    supabase,
    logMailAudit,
  ])

  const handleSend = useCallback(async () => {
    if (weekNumbers.length === 0) {
      toast.error("No weeks selected")
      return
    }
    if (resolvedRecipients.length === 0) {
      toast.error("No recipients selected")
      return
    }
    if (selectedContentChoices.size === 0) {
      toast.error("Select at least one content item")
      return
    }
    if (selectedContentChoices.has("knowledge_sharing_session") && allKssDocs.length === 0) {
      toast.error("No Knowledge Sharing Session files uploaded for the selected weeks")
      return
    }
    if (selectedContentChoices.has("minutes_of_meeting") && allMinutesDocs.length === 0) {
      toast.error("No Minutes of Meeting files uploaded for the selected weeks")
      return
    }
    if (
      sendTiming !== "now" &&
      (selectedContentChoices.has("knowledge_sharing_session") || selectedContentChoices.has("minutes_of_meeting"))
    ) {
      toast.error("Stored file send options can only be sent immediately")
      return
    }

    // ── Scheduled ──────────────────────────────────────────────────────────
    if (sendTiming === "scheduled") {
      if (!scheduledDate) {
        toast.error("Please set a scheduled date")
        return
      }
      const scheduledDateTime = new Date(`${scheduledDate}T${scheduledTime}`)
      if (scheduledDateTime <= new Date()) {
        toast.error("Scheduled time must be in the future")
        return
      }

      const includeWeeklyReport = selectedContentChoices.has("weekly_report")
      const includeActionTracker = selectedContentChoices.has("action_points_autogenerated")

      if (includeActionTracker) {
        toast.error("Exact Action Points PDF mail send is currently available with Send Now only")
        return
      }

      let scheduleContentChoice: "weekly_report" | "action_tracker" | "both"
      if (includeWeeklyReport && includeActionTracker) {
        scheduleContentChoice = "both"
      } else if (includeWeeklyReport) {
        scheduleContentChoice = "weekly_report"
      } else if (includeActionTracker) {
        scheduleContentChoice = "action_tracker"
      } else {
        toast.error("Only Weekly Report and Action Points can be scheduled")
        return
      }

      const { error } = await supabase.from("weekly_report_schedules").insert({
        schedule_type: "one_time",
        meeting_week: weekNumbers[0],
        meeting_weeks: weekNumbers,
        meeting_year: yearNumber,
        recipients: resolvedRecipients,
        content_choice: scheduleContentChoice,
        next_run_at: scheduledDateTime.toISOString(),
      })

      if (error) {
        toast.error("Failed to save schedule: " + error.message)
        return
      }

      toast.success(
        `Email scheduled for ${scheduledDateTime.toLocaleString("en-GB", {
          weekday: "short",
          day: "numeric",
          month: "short",
          hour: "2-digit",
          minute: "2-digit",
        })}`
      )
      fetchSchedules()
      return
    }

    // ── Recurring ──────────────────────────────────────────────────────────
    if (sendTiming === "recurring") {
      const days = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
      const targetDay = days.indexOf(recurringDay)
      const now = new Date()
      const currentDay = now.getDay()
      let daysUntil = targetDay - currentDay
      const [h, m] = recurringTime.split(":")
      const targetMinutes = parseInt(h, 10) * 60 + parseInt(m, 10)
      const nowMinutes = now.getHours() * 60 + now.getMinutes()
      if (daysUntil < 0 || (daysUntil === 0 && nowMinutes >= targetMinutes)) daysUntil += 7
      const nextRun = new Date(now)
      nextRun.setDate(now.getDate() + daysUntil)
      nextRun.setHours(parseInt(h, 10), parseInt(m, 10), 0, 0)

      const includeWeeklyReport = selectedContentChoices.has("weekly_report")
      const includeActionTracker = selectedContentChoices.has("action_points_autogenerated")
      if (includeActionTracker) {
        toast.error("Exact Action Points PDF mail send is currently available with Send Now only")
        return
      }
      if (!includeWeeklyReport && !includeActionTracker) {
        toast.error("Recurring mode supports Weekly Report and Action Points only")
        return
      }

      const recurringContentChoice: "weekly_report" | "action_tracker" | "both" =
        includeWeeklyReport && includeActionTracker ? "both" : includeWeeklyReport ? "weekly_report" : "action_tracker"

      const { error } = await supabase.from("weekly_report_schedules").insert({
        schedule_type: "recurring",
        recipients: resolvedRecipients,
        content_choice: recurringContentChoice,
        send_day: recurringDay,
        send_time: recurringTime,
        next_run_at: nextRun.toISOString(),
      })

      if (error) {
        toast.error("Failed to save recurring schedule: " + error.message)
        return
      }

      toast.success(`Recurring weekly email set for every ${capitalize(recurringDay)} at ${recurringTime}`)
      fetchSchedules()
      return
    }

    // ── Immediate ──────────────────────────────────────────────────────────
    await doSend()
  }, [
    resolvedRecipients,
    selectedContentChoices,
    allKssDocs,
    allMinutesDocs,
    sendTiming,
    scheduledDate,
    scheduledTime,
    recurringDay,
    recurringTime,
    weekNumbers,
    yearNumber,
    supabase,
    fetchSchedules,
    doSend,
  ])

  const deactivateSchedule = useCallback(
    async (id: string) => {
      const { error } = await supabase.from("weekly_report_schedules").update({ is_active: false }).eq("id", id)
      if (error) {
        toast.error("Failed to deactivate schedule")
      } else {
        toast.success("Schedule deactivated")
        fetchSchedules()
      }
    },
    [supabase, fetchSchedules]
  )

  return { isSending, sendResult, handleSend, deactivateSchedule }
}
