"use client"

import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { FileText, ClipboardList, CalendarDays } from "lucide-react"

type ContentChoice =
  | "weekly_report"
  | "action_points_autogenerated"
  | "knowledge_sharing_session"
  | "minutes_of_meeting"
  | "action_points_manual"

interface ContentOption {
  value: ContentChoice
  label: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  icon: any
  desc: string
  disabled: boolean
}

interface WeeklySummaryFormProps {
  weekNumber: number
  yearNumber: number
  setWeekNumber: (w: number) => void
  setYearNumber: (y: number) => void
  weekOptions: number[]
  yearOptions: number[]
  contentOptions: ContentOption[]
  selectedContentChoices: Set<ContentChoice>
  toggleContentChoice: (choice: ContentChoice, disabled?: boolean) => void
  adminHrPreparers: string[]
  selectedPreparedBy: string
  setSelectedPreparedBy: (name: string) => void
}

export function WeeklySummaryForm({
  weekNumber,
  yearNumber,
  setWeekNumber,
  setYearNumber,
  weekOptions,
  yearOptions,
  contentOptions,
  selectedContentChoices,
  toggleContentChoice,
  adminHrPreparers,
  selectedPreparedBy,
  setSelectedPreparedBy,
}: WeeklySummaryFormProps) {
  return (
    <>
      {/* Week Selection */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-lg">
            <CalendarDays className="h-5 w-5 text-green-600" />
            Meeting Week
          </CardTitle>
          <CardDescription>Choose which general meeting week to send</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap items-end gap-4">
            <div className="space-y-2">
              <Label htmlFor="week-select">Meeting Week</Label>
              <Select value={String(weekNumber)} onValueChange={(v) => setWeekNumber(Number(v))}>
                <SelectTrigger id="week-select" className="w-[140px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {weekOptions.map((w) => (
                    <SelectItem key={w} value={String(w)}>
                      Week {w}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="year-select">Year</Label>
              <Select value={String(yearNumber)} onValueChange={(v) => setYearNumber(Number(v))}>
                <SelectTrigger id="year-select" className="w-[120px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {yearOptions.map((y) => (
                    <SelectItem key={y} value={String(y)}>
                      {y}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="text-muted-foreground space-y-1 text-sm">
              <p>
                All Content: <Badge variant="outline">Week {weekNumber}</Badge>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Content Choice */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-lg">
            <FileText className="h-5 w-5 text-blue-600" />
            Content to Send
          </CardTitle>
          <CardDescription>Tick one or more items to include in this email</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            {contentOptions.map((opt) => {
              const checked = selectedContentChoices.has(opt.value)
              return (
                <label
                  key={opt.value}
                  className={`flex items-start gap-3 rounded-lg border p-3 transition-colors ${
                    opt.disabled
                      ? "bg-muted/20 opacity-60"
                      : checked
                        ? "border-green-600 bg-green-50/60"
                        : "hover:bg-muted/40"
                  }`}
                >
                  <Checkbox
                    checked={checked}
                    disabled={opt.disabled}
                    onCheckedChange={() => toggleContentChoice(opt.value, opt.disabled)}
                    className="mt-0.5"
                  />
                  <opt.icon className="text-muted-foreground mt-0.5 h-4 w-4 shrink-0" />
                  <div className="min-w-0">
                    <div className="text-sm font-semibold">{opt.label}</div>
                    <div className="text-muted-foreground text-xs">{opt.desc}</div>
                    {opt.disabled ? (
                      <div className="text-destructive mt-1 text-[11px]">Upload this in Reports first</div>
                    ) : null}
                  </div>
                </label>
              )
            })}
          </div>

          <div className="mt-4 rounded-lg border p-4">
            <div className="mb-2 flex items-center justify-between gap-2">
              <Label htmlFor="prepared-by">Prepared by</Label>
              <Badge variant="outline">Admin &amp; HR only</Badge>
            </div>
            <Select value={selectedPreparedBy} onValueChange={setSelectedPreparedBy}>
              <SelectTrigger id="prepared-by" className="w-full">
                <SelectValue placeholder="Select a name" />
              </SelectTrigger>
              <SelectContent>
                {adminHrPreparers.length > 0 ? (
                  adminHrPreparers.map((name) => (
                    <SelectItem key={name} value={name}>
                      {name}
                    </SelectItem>
                  ))
                ) : (
                  <SelectItem value="ACOB Team">ACOB Team</SelectItem>
                )}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>
    </>
  )
}

// Re-export icons used by parent
export { FileText, ClipboardList }
