-- Add department column to cbt_questions if not exists
ALTER TABLE public.cbt_questions ADD COLUMN IF NOT EXISTS department text;

-- Insert review cycles
-- Q3 2025 (Closed)
INSERT INTO public.review_cycles (id, name, start_date, end_date, review_type, status)
VALUES ('aaaaaaaa-0001-4000-a000-000000000003', 'Q3 2025 Performance Review', '2025-07-01', '2025-09-30', 'quarterly', 'closed')
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name, status = EXCLUDED.status, start_date = EXCLUDED.start_date, end_date = EXCLUDED.end_date;

-- Q4 2025 (Active)
INSERT INTO public.review_cycles (id, name, start_date, end_date, review_type, status)
VALUES ('aaaaaaaa-0001-4000-a000-000000000004', 'Q4 2025 Performance Review', '2025-10-01', '2025-12-31', 'quarterly', 'active')
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name, status = EXCLUDED.status, start_date = EXCLUDED.start_date, end_date = EXCLUDED.end_date;

-- Close other cycles to ensure only Q4 2025 is active as requested
UPDATE public.review_cycles 
SET status = 'closed' 
WHERE id != 'aaaaaaaa-0001-4000-a000-000000000004';

-- Seed 100 questions for Q4 2025 Performance Review (10 per department)
-- Accounts (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'What is the standard accounting treatment for capital expenditure on solar panels at ACOB?', 'Capitalized as property, plant and equipment', 'Expensed immediately in the current month', 'Recorded as a liability', 'Ignored until project is sold', 'A', 'Capital expenditures on solar installations are capitalized as fixed assets and depreciated over time.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'How is depreciation calculated for solar battery banks at ACOB?', 'Straight-line over expected battery life', 'Double-declining balance method', 'Units of production method', 'Random allocation based on revenue', 'A', 'Battery bank depreciation is typically calculated using the straight-line method over its useful lifecycle.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'Which document is required to initiate a vendor payment for solar materials?', 'Purchase invoice and verified delivery note', 'Employee leave approval form', 'Verbal confirmation from technical staff', 'A draft sales presentation', 'A', 'Finance requires a verified purchase invoice matching the signed delivery note to process vendor payments.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'What is the purpose of reconciling accounts receivable from solar microgrid customers?', 'To match payments with energy consumption records', 'To decrease customer power allocations', 'To audit local government taxes', 'To increase monthly tariff rates', 'A', 'Reconciliation ensures payments match meter records to avoid billing discrepancies.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'Under what condition is revenue recognized for a solar installation project?', 'Upon completion of installation and customer acceptance', 'Immediately when the deposit is received', 'When materials arrive in the warehouse', 'When the team starts site survey', 'A', 'Revenue is recognized when the service is fully rendered and formally accepted by the customer.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'What is the primary role of the finance department in solar asset management?', 'Tracking depreciation and asset valuation', 'Cleaning solar panels at site locations', 'Writing software code for smart meters', 'Configuring inverter telemetry systems', 'A', 'Finance is responsible for tracking depreciation, asset valuation, and capital asset registration.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'What tax incentive is generally applicable to solar equipment imported by ACOB in Nigeria?', 'Import duty exemptions on clean energy products', 'Income tax surcharges', 'Corporate luxury taxes', 'Zero-tariff export bonuses', 'A', 'Nigeria provides import duty waivers and VAT exemptions on certain clean energy components.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'How does ACOB classify battery inventory waiting to be deployed?', 'Current assets', 'Long-term liabilities', 'Retained earnings', 'Operating expenses', 'A', 'Inventory held for deployment is classified under current assets on the balance sheet.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'Why is petty cash reconciliation critical for field technicians at installation sites?', 'To track minor localized logistics and materials expenses', 'To pay for international shipping fees', 'To purchase heavy-duty hybrid inverters', 'To pay monthly office rent', 'A', 'Petty cash handles minor field incidentals and local purchases that require direct tracing.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Accounts', 'Which metric is used to evaluate the financial viability of a new microgrid project?', 'Net Present Value (NPV) and Payback Period', 'Total page views on the company website', 'The count of active staff members', 'The distance from head office to site', 'A', 'Financial feasibility uses Net Present Value (NPV), IRR, and Payback Period calculation.', true);

-- Admin & HR (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'What is the standard response time for HR regarding employee leave requests?', '48 business hours', 'One business week', 'Immediately on phone call', 'No response is needed', 'A', 'HR aims to process leave requests within 48 business hours of system submission.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'Which policy governs the safety protocol for field technicians working on solar roofs?', 'ACOB Health and Safety Policy', 'Corporate Social Responsibility Code', 'IT Device Allocation Guidelines', 'Annual Marketing Guidelines', 'A', 'The Health & Safety Policy defines procedures, safety gear, and fall protection on rooftops.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'How often are standard performance review cycles conducted at ACOB?', 'Quarterly', 'Every two years', 'Daily before work', 'Only when staff requests a promotion', 'A', 'Performance reviews are run quarterly to keep goals and KPIs aligned.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'What is the correct procedure for reporting a workplace safety incident?', 'Report immediately to the department lead and HR', 'Post it on personal social media', 'Wait until the quarterly PMS review', 'Tell a client during project handover', 'A', 'All safety incidents must be reported immediately to the supervisor and HR for investigation.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'Which tool does ACOB use for internal employee staff directory and sign-offs?', 'ACOB Signature Creator & ERP', 'A local notebook at reception', 'External WhatsApp groups only', 'Microsoft Outlook templates only', 'A', 'The internal ERP and Signature Creator serve as the official platform for staff details and sign-offs.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'What is the minimum notice period required for voluntary resignation?', 'One month', 'One week', 'Three months', 'No notice is needed', 'A', 'A minimum of one month notice or payment in lieu of notice is required for resignation.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'Who is responsible for approving specialized safety training for Technical staff?', 'HR department and Technical Head', 'The customer at the local site', 'The logistics driver', 'Third-party auditors only', 'A', 'Safety training is authorized jointly by HR and the Technical Department lead.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'What is the primary objective of the quarterly PMS (Performance Management System) review?', 'To evaluate KPIs, goals, and core behaviors', 'To distribute monthly salaries', 'To assign site vehicle keys', 'To inspect office cleaning logs', 'A', 'The PMS review measures employee achievement, KPIs, and alignment with corporate values.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'Which document must new employees submit within their first week of onboarding?', 'Signed employment contract and bank details', 'Prior employment sales records', 'Their school transcripts physically', 'List of personal devices owned', 'A', 'Onboarding requires a signed contract and payment details for HR registration.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Admin & HR', 'How is overtime calculated for admin staff during weekend deployments?', 'Per hour rate multiplied by weekend multiplier', 'A flat bonus added at the end of the year', 'Given as additional annual leave days only', 'Decided by verbal agreement weekly', 'A', 'Weekend overtime follows a calculated rate based on base hourly pay and weekend coefficients.', true);

-- Business, Growth and Innovation (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'What is ACOB''s primary target market for commercial solar microgrids?', 'Off-grid communities and commercial industrial centers', 'Residential apartments in urban cities only', 'International shipping ports only', 'Government offices in federal capitals', 'A', 'ACOB focuses on off-grid communities and commercial/industrial sites requiring stable power.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'Which solar product offering focuses on residential backup power?', 'ACOB Home Smart Solar System', 'ACOB Industrial Grid Max', 'ACOB Micro-Hydro Plus', 'ACOB Wind Turbine Lite', 'A', 'The ACOB Home Smart Solar System is optimized for residential hybrid backups.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'What is the first step in assessing a new community for microgrid deployment?', 'Conducting an energy demand and load profile assessment', 'Signing a land lease agreement immediately', 'Shipping solar panels to the site', 'Publishing a news press release', 'A', 'BGI must first assess energy demand and load profiles before sizing or proposing a microgrid.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'How does the Business Growth team evaluate potential partnerships with local developers?', 'Due diligence on track record and regional regulatory compliance', 'Relying solely on social media popularity', 'Signing agreements without prior checks', 'Choosing partners based on lowest cost only', 'A', 'Partner selection requires thorough due diligence on experience, assets, and regulatory compliance.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'What is the purpose of conducting a competitor analysis in the Nigerian solar market?', 'To identify pricing trends and product differentiation opportunities', 'To merge with rival installation companies', 'To set legally fixed price ceilings with competitors', 'To reduce the quality of imported inverters', 'A', 'Competitor analysis allows ACOB to identify market gaps, pricing, and value differentiation.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'Which metric measures the customer conversion rate of BGI marketing campaigns?', 'Percentage of leads converted to contracted projects', 'Total number of website visits per week', 'Average size of installed inverter systems', 'Count of emails sent to prospective clients', 'A', 'The conversion rate measures what percentage of qualified leads sign installation contracts.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'What key value proposition does ACOB offer to commercial customers over diesel generators?', 'Lower long-term operational costs and zero emissions', 'A lower initial hardware purchase cost', 'Total independence from battery backup systems', 'Unlimited power output without limitations', 'A', 'Solar microgrids cut diesel fuel costs, lower operating expenses, and eliminate carbon emissions.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'Why is customer feedback critical after the first month of microgrid operation?', 'To calibrate tariff plans and monitor system stability', 'To request full upfront payment for the next year', 'To disable smart meters remotely', 'To redesign solar panel roof mounts', 'A', 'Feedback helps BGI adjust tariffs, verify satisfaction, and check system sizing limits.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'Which strategy is used to expand ACOB''s footprint in rural areas?', 'Public-Private Partnerships and community stakeholder alignment', 'Massive advertising on national television only', 'Offering free power indefinitely without tariffs', 'Installing systems without community consent', 'A', 'Rural mini-grids succeed through PPP frameworks and deep alignment with local leaders.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Business, Growth and Innovation', 'What is the primary goal of the Innovation team regarding energy storage?', 'Integrating cost-effective lithium-iron phosphate battery systems', 'Reverting all grid designs to lead-acid batteries', 'Eliminating battery backups from solar setups', 'Developing disposal methods for nuclear waste', 'A', 'Innovation seeks to deploy LFP battery technologies due to superior lifecycle and stability.', true);

-- Corporate Services (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'Which department manages vehicle fleet logistics for site installations?', 'Corporate Services', 'Finance and Accounts', 'Software Development Desk', 'Stakeholder Engagement', 'A', 'Corporate Services oversees vehicle allocations, maintenance, and logistics for deployments.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'What is the procedure for requesting a company vehicle for field installation?', 'Submit a fleet booking request via ERP', 'Call the driver directly without notice', 'Take keys from reception without log entry', 'Ask the client to provide transport', 'A', 'Vehicle requests require formal logging and approval via the ERP fleet management module.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'Who handles procurement of office supplies and non-technical equipment?', 'Corporate Services Procurement Desk', 'The solar installation technician', 'Individual department heads directly from personal cash', 'The security team at the gate', 'A', 'Non-technical procurement is centralized under Corporate Services to track budget lines.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'What is the main objective of facilities management at ACOB headquarters?', 'Ensuring continuous power, water, and building maintenance', 'Writing marketing brochures for microgrids', 'Reviewing candidate resumes for HR', 'Programming data telemetry gateways', 'A', 'Facilities management ensures the corporate office has stable operations, power, and safety.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'Which policy regulates the usage of company-issued laptops and devices?', 'IT & Corporate Services Asset Policy', 'Standard Finance Reimbursement Guide', 'Site Installation Checklist', 'The Board of Directors Charter', 'A', 'The IT & Asset Policy outlines the care, updates, and returned terms of company hardware.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'What is the retention period for corporate physical documents at ACOB?', 'Seven years', 'One month', 'Indefinitely without archiving', 'No retention is required', 'A', 'Official corporate files and receipts are archived for seven years for tax and legal audits.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'Who should be contacted for office space allocation changes?', 'Head of Corporate Services', 'The building security officer', 'The payroll manager', 'The site project supervisor', 'A', 'Space planning and office allocation are directed by Corporate Services administration.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'How are vendor service level agreements (SLAs) managed for office security?', 'Reviewed annually by Corporate Services', 'Verbally checked by reception monthly', 'Ignored after contract signing', 'Managed by the technical engineer', 'A', 'Corporate Services reviews security vendor contracts and SLAs annually for compliance.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'What safety equipment must be present in all company utility vehicles?', 'First-aid kit, fire extinguisher, and reflective triangles', 'Spare solar panels and cabling', 'Spare inverter screen modules', 'Marketing banners and office supplies', 'A', 'Vehicle safety compliance requires standard emergency equipment in all fleet units.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Corporate Services', 'What is the correct procedure for disposing of damaged office furniture?', 'Write-off authorization by Finance and disposal by Corporate Services', 'Selling it directly without approval', 'Leaving it at a site location', 'Burning it behind the warehouse', 'A', 'Disposal of any fixed asset requires depreciation checks, write-off sign-off, and formal discard.', true);

-- IT and Communications (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'What is the correct format for an official ACOB employee email address?', 'username@acoblighting.com', 'username@gmail.com', 'username@acob.org', 'firstname.lastname@outlook.com', 'A', 'The standard corporate domain for employee emails is acoblighting.com.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'Which platform does ACOB ERP run on for data storage?', 'Supabase Database', 'Local Excel sheets on OneDrive', 'Google Firebase console', 'Oracle On-Premise Servers', 'A', 'The ACOB ERP utilizes Supabase PostgreSQL database for secure, structured data storage.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'What security measure must be active on all company laptops accessing the ERP?', 'Multi-factor authentication and device encryption', 'A simple four-digit screen PIN code', 'No password for quick access', 'Public guest browser profiles only', 'A', 'Company device security mandates strong passwords, MFA, and drive encryption.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'How do employees report a software bug or access issue in the ERP?', 'Create a ticket on the Help Desk page', 'Send a direct message on WhatsApp', 'Leave an anonymous physical note', 'Wait until the quarterly PMS review', 'A', 'All software support and bugs must be logged formally via the Help Desk page in the ERP.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'Which protocol is used for remote data monitoring of solar microgrids?', 'Modbus TCP or GSM/GPRS telemetry', 'Simple HTTP requests without auth', 'Bluetooth local connections only', 'FTP file uploads weekly', 'A', 'Real-time telemetry uses industrial protocols like Modbus TCP, RTU, and cellular GPRS links.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'What is the daily backup frequency for ACOB''s production database?', 'Automated daily snapshot backups', 'Weekly manual exports to flash drives', 'No backups are required', 'Monthly database replications', 'A', 'The production database is protected by automated, daily snapshot backups.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'Which tool is used to manage official email signatures at ACOB?', 'ACOB Signature Creator', 'Microsoft Paint templates', 'A shared Word document', 'Photoshop graphics editing', 'A', 'The ACOB Signature Creator enforces standardized, branded email signatures for all staff.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'What is the correct action if an employee suspects their ERP password is compromised?', 'Reset password immediately and notify IT', 'Continue using it to avoid profile setup delays', 'Write the password down on a sticky note', 'Tell other department staff members', 'A', 'Compromised passwords must be changed immediately and logged with IT security.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'Why is bandwidth monitoring important for remote microgrid smart meters?', 'To control data costs and ensure continuous telemetry', 'To increase the speed of customer internet', 'To change the inverter output voltage', 'To audit local utility company grids', 'A', 'Telemetry monitoring controls data budgets and prevents sudden communications downtime.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'IT and Communications', 'What is the default password policy for the ACOB ERP?', 'Minimum 8 characters with numbers, symbols, and uppercase letters', 'Any 4 characters', 'Only letters allowed', 'Password must match employee ID', 'A', 'ERP password policy requires complexity to prevent unauthorized access to staff records.', true);

-- Operations and Maintenance (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'How often should solar panel cleaning be scheduled in high-dust regions?', 'Bi-weekly or monthly depending on dirt buildup', 'Once every year in rainy season', 'Only when the panel fails completely', 'Daily at noon when sun is highest', 'A', 'Dust deposits cause panel shading; cleaning is scheduled bi-weekly or monthly for yield optimization.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'What is the primary indicator of a failing lead-acid battery cell in a bank?', 'Significant voltage drop under load and high temperature', 'A change in the outer casing color', 'A slight increase in output current', 'No visible or electrical symptoms', 'A', 'Failing battery cells present significant voltage drops under load, cell temperature rises, or swelling.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'Which tool is used to monitor real-time power generation of a solar inverter?', 'Inverter portal or integrated SCADA telemetry', 'A standard handheld voltmeter only', 'Checking the inverter cooling fan speed', 'Looking at panel reflection from the ground', 'A', 'Monitoring is performed via connected telemetry software/portals or SCADA systems.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'What is the first step in troubleshooting a complete system blackout at a microgrid?', 'Check safety breakers and verify inverter fault codes', 'Re-wire the solar panel arrays immediately', 'Add more distilled water to LFP batteries', 'Replace the main grid transformer', 'A', 'Troubleshooting starts with inspecting circuit breakers and reading system error codes.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'Why is preventive maintenance of diesel backup generators necessary?', 'To ensure immediate startup during prolonged low-solar periods', 'To keep the generator running 24/7 constantly', 'To reduce the fuel cost to zero', 'To bypass the battery bank completely', 'A', 'Generators act as emergency backup and must be maintained to start reliably when called upon.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'What is the standard torque specification for solar structure mounting bolts?', 'Varies by bolt size, typically checked with a calibrated torque wrench', 'As tight as possible until the bolt shears off', 'Finger-tight only to allow structure movement', 'No specific torque spec is required', 'A', 'Mounting structural bolts must be tightened to exact specifications using torque tools.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'How is battery State of Charge (SoC) calibrated on smart battery monitors?', 'By performing a full charge and discharge cycle calibration', 'By resetting the inverter system daily', 'By adding acid to the lithium battery cells', 'By changing the solar charge controller limit', 'A', 'Calibration requires charging to 100% and discharging to empty to align the battery monitor algorithms.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'What safety gear must be worn when working inside a live combiner box?', 'Insulated gloves, safety glasses, and arc-flash clothing', 'Standard office uniform and sneakers', 'No specialized gear is required if power is low', 'Steel-toed boots only without hand protection', 'A', 'Live combiner box work poses electrical shock and arc-flash hazards; proper personal protective equipment is mandatory.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'What does a high grounding resistance reading indicate at a microgrid site?', 'Inadequate grounding system or dry soil conditions', 'An extremely safe electrical circuit', 'Excessive solar energy absorption', 'A failing lithium battery cell', 'A', 'High grounding resistance indicates poor grounding safety path, risking surge damage.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Operations and Maintenance', 'Which metric is used to measure overall microgrid uptime?', 'System Availability Factor', 'Total daily energy consumption', 'Peak solar generation capacity', 'Number of active customer meters', 'A', 'Uptime and operational reliability are tracked using the System Availability Factor (%).', true);

-- Project (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'What is the primary project management tool used to track solar installation timelines?', 'Gantt charts and ERP project task boards', 'Personal diaries of the installation crew', 'Client WhatsApp chat history', 'Weekly verbal summaries at lunch', 'A', 'Official projects are managed and tracked using Gantt charts and the ERP project task board.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'What is the first phase of the ACOB solar project lifecycle?', 'Feasibility study and site survey approval', 'Procuring panels from suppliers', 'Mounting structural rails on the roof', 'Client final project handover sign-off', 'A', 'All solar projects begin with a comprehensive site assessment and feasibility approval.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'Who is responsible for coordinating local community labor during site construction?', 'The assigned Project Manager', 'The corporate accounting officer', 'The local utility company head', 'The HR recruiting officer at headquarters', 'A', 'The Project Manager coordinates local site operations, community labor, and materials deployment.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'What document defines the scope, budget, and timeline of a solar installation?', 'Project Charter or Scope of Work', 'An informal email list of items', 'The company employee handbook', 'The inverter user manual', 'A', 'The Scope of Work (SOW) serves as the binding project plan defining boundaries, tasks, and budgets.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'What is the purpose of a Post-Implementation Review (PIR) in project management?', 'To document lessons learned and evaluate project success', 'To recalculate employee tax lines', 'To clean the solar panels before leaving', 'To pitch a new project proposal to a client', 'A', 'PIR reviews capture learning points, audit budget variances, and evaluate project outcomes.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'How are project budget variances managed at ACOB?', 'Reported weekly to the Project Director and Finance team', 'Ignored if they are under one million Naira', 'Compensated by using lower quality wiring', 'Charged directly to the technician''s salary', 'A', 'Budget deviations must be caught early and reported weekly to Finance and Project Directors.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'What is the role of a project stakeholder alignment meeting?', 'To secure community support and resolve land use approvals', 'To train the technical staff on wiring', 'To finalize inverter pricing with manufacturers', 'To audit internal software servers', 'A', 'Stakeholder alignment ensures host community cooperation and handles land/use licensing.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'Which document must be signed by the client upon completion of installation?', 'Project Handover and Acceptance Certificate', 'A generic survey form', 'The vehicle logbook of the delivery truck', 'An employment application form', 'A', 'The Handover Certificate confirms formal system completion and triggers final billing.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'What is a critical path in project scheduling?', 'The sequence of stages determining the minimum project duration', 'The easiest route to drive to the installation site', 'The list of materials with the lowest price', 'The safety protocol for roof climbing work', 'A', 'The critical path represents the sequence of dependent tasks that directly dictates the project completion date.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Project', 'How does ACOB mitigate the risk of delivery delays for imported inverters?', 'By maintaining buffer stock and ordering long-lead items early', 'By buying from local retail markets at any cost', 'By delaying site surveys until materials arrive', 'By using standard shipping instead of air freight', 'A', 'ACOB mitigates supply chain risks by ordering long-lead hardware early and stocking buffers.', true);

-- Regulatory and Compliance (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'Which regulatory body licenses mini-grid operations in Nigeria?', 'Nigerian Electricity Regulatory Commission (NERC)', 'Standard Organization of Nigeria (SON) only', 'Federal Ministry of Works', 'Nigerian Communications Commission (NCC)', 'A', 'NERC is the primary regulator licensing and monitoring commercial mini-grids in Nigeria.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'What environmental document is required before installing a large-scale solar farm?', 'Environmental and Social Impact Assessment (ESIA)', 'A standard fire safety certificate', 'A local government construction permit only', 'Corporate environmental tax return', 'A', 'Large installations require an ESIA to study and mitigate local ecological impacts.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'Under NERC regulations, what tariff structure is approved for mini-grids?', 'MYTO - Multi-Year Tariff Order or negotiated tariffs', 'Flat rates fixed by local communities', 'Unregulated free-market pricing', 'Tariffs based on customer income levels only', 'A', 'Tariff designs follow NERC MYTO frameworks or formal cost-reflective approvals.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'What is the maximum capacity for a self-generation permit without full licensing in Nigeria?', '1 Megawatt (MW)', '100 Kilowatts (kW)', '10 Megawatts (MW)', 'There is no limit for self-generation', 'A', 'Under current regulations, self-generation up to 1MW is exempted from full licensing but requires notification.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'How does ACOB ensure compliance with local content regulations?', 'By hiring local community members for site construction and security', 'By importing all materials and labor from Europe', 'By avoiding rural site deployments entirely', 'By paying bribes to local officials', 'A', 'ACOB complies with local content policies by employing and training local community members.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'What is the penalty for operating a commercial mini-grid without NERC registration?', 'Fines, system shutdown, or seizure of equipment', 'A warning letter only', 'Suspension of employee signature credentials', 'No legal penalty exists', 'A', 'Operating unpermitted commercial mini-grids exposes the company to severe regulatory fines and equipment seizure.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'Which standard governs electrical installation safety in Nigeria?', 'NEMSA - Nigerian Electricity Management Services Agency standards', 'Nigerian Customs Service import standard', 'The local building association rules', 'American Petroleum Institute standards', 'A', 'NEMSA is legally mandated to test, inspect, and certify all electrical installations in Nigeria.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'Why is a land-lease agreement registered with the local state ministry of land?', 'To secure long-term land use rights and avoid legal disputes', 'To get discounts on local construction materials', 'To register the solar panels for asset insurance', 'To bypass NERC licensing requirements', 'A', 'Formal registration secures leasehold titles, preventing land disputes during the 20-25 year project life.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'How often must ACOB submit compliance reports to NERC?', 'Semi-annually or annually as specified in the permit', 'Weekly via email', 'Only after a system failure occurs', 'Every five years during audit reviews', 'A', 'Mini-grid operators are required to submit operational reports semi-annually or annually.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Regulatory and Compliance', 'What is the role of NEMSA regarding newly installed solar microgrids?', 'To inspect, test, and certify the safety of the installation', 'To invoice customers for electrical tariffs', 'To source solar panel components from overseas', 'To write software code for telemetry meters', 'A', 'NEMSA conducts technical inspections and issues safety certificates before grids can go live.', true);

-- Technical (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'What is the primary function of a solar charge controller?', 'To regulate voltage and current from panels to prevent battery overcharging', 'To convert DC power to high voltage AC power', 'To track the physical movement of the sun', 'To switch on backup diesel generators automatically', 'A', 'Charge controllers manage battery charging profiles and prevent overcharging and deep discharge.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'What is the difference between a string inverter and a microinverter?', 'String inverter manages a group of panels; microinverter manages one panel', 'String inverter converts AC to DC; microinverter converts DC to AC', 'String inverter requires batteries; microinverter does not', 'There is no functional difference', 'A', 'String inverters process combined DC power from array strings; microinverters mount behind individual panels.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'Why are lithium-iron phosphate (LFP) batteries preferred over lead-acid at ACOB?', 'Higher energy density, longer cycle life, and deeper discharge depth', 'They are much cheaper to purchase upfront', 'They do not require any electronic monitoring systems (BMS)', 'They have a shorter charging time but lower safety factor', 'A', 'LFP batteries offer superior longevity (up to 4000-6000 cycles), safe operation, and 80-90% Depth of Discharge.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'What does the term "Voc" represent in solar panel specifications?', 'Open-Circuit Voltage', 'Voltage at maximum operating current', 'Vector Over-Current protection threshold', 'Variable Output Current limit', 'A', 'Voc is the maximum voltage a panel produces when disconnected from any load or circuit.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'What is the purpose of a bypass diode in a solar panel?', 'To allow current to flow around shaded cells, minimizing power loss', 'To increase the output voltage of the panel', 'To protect the inverter from battery back-feed', 'To convert direct current into alternating current', 'A', 'Bypass diodes prevent shaded cells from acting as resistors and causing hot-spot damage.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'How is the total capacity of a battery bank calculated in kilowatt-hours (kWh)?', 'Voltage multiplied by Ampere-hour capacity divided by 1000', 'Voltage divided by current output', 'Ampere-hour capacity multiplied by inverter efficiency', 'Total weight of battery cells divided by daily hours', 'A', 'Energy capacity in kWh is calculated as: (V * Ah) / 1000.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'What is the primary cause of thermal runaway in lithium batteries?', 'Overcharging, external short circuits, or high temperatures', 'Operating the battery at extremely low current rates', 'Charging the battery below 10% capacity', 'Exposure to low-intensity ambient noise', 'A', 'Thermal runaway results from excessive heat generation caused by short circuits, overcharging, or physical damage.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'What is the function of an automatic transfer switch (ATS) in a hybrid solar system?', 'To seamlessly switch load between solar, batteries, and backup grid', 'To raise solar panel inclination during winter months', 'To record billing tariffs for residential meters', 'To regulate the operating speed of generator engines', 'A', 'The ATS safely switches loads between power sources to maintain supply continuity without feedback.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'Why is cable sizing critical in low-voltage DC solar circuits?', 'To minimize voltage drop and prevent cable overheating', 'To increase the maximum speed of telemetry data', 'To matches the color codes of inverters', 'To allow easier bending around structural corners', 'A', 'DC circuits carry high currents at low voltages; adequate sizing limits resistance losses and fire hazards.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Technical', 'What electrical safety device protects solar arrays from lightning surges?', 'Surge Protective Device (SPD)', 'Residual Current Device (RCD)', 'Molded Case Circuit Breaker (MCCB)', 'Thermal Overload Relay', 'A', 'SPDs divert high-voltage lightning surges safely to the grounding grid, protecting electronics.', true);

-- Executive Management (10 questions)
INSERT INTO public.cbt_questions (review_cycle_id, department, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, is_active) VALUES
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'What is ACOB''s long-term vision regarding renewable energy capacity in West Africa?', 'To deploy over 50MW of clean solar power by 2030', 'To purchase regional oil refining assets', 'To manufacture petrol generators locally', 'To completely exit the clean energy sector', 'A', 'ACOB''s corporate strategy Targets deploying 50MW+ of solar capacity in West Africa by 2030.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'Which core value focuses on transparency and ethical behavior at ACOB?', 'Integrity', 'Velocity', 'Hierarchy', 'Exclusivity', 'A', 'Integrity is a core corporate value guiding ethics, customer trust, and corporate governance.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'Who approves the annual strategic business plan and budget for ACOB?', 'The Board of Directors', 'The local community leaders', 'Individual project managers', 'Third-party accounting consultants', 'A', 'The Board of Directors reviews and signs off on the corporate strategy, audits, and annual budgets.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'What is the primary role of Executive Management during quarterly reviews?', 'To align department goals with overall corporate strategy', 'To verify daily attendance stamps of reception staff', 'To purchase electrical wiring for site projects', 'To write code patches for the help desk system', 'A', 'Executive management reviews quarterly results to ensure alignment with strategic KPI benchmarks.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'How does Executive Management evaluate the success of new business ventures?', 'By reviewing Return on Investment (ROI) and social impact metrics', 'By checking total followers on social media channels', 'By estimating the total weight of imported materials', 'By the number of internal department meetings held', 'A', 'Venture viability is measured by financial returns (ROI, NPV) and clean energy access indicators.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'What is the corporate policy regarding sustainable development and ESG (Environmental, Social, Governance)?', 'To integrate sustainability into all project lifecycles', 'To prioritize short-term profit over environmental impact', 'To bypass local environmental impact assessments', 'To hire foreign labor exclusively for construction', 'A', 'ESG criteria are integrated into project planning to ensure community and ecological sustainability.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'Who represents ACOB in high-level governmental and international investment meetings?', 'The Executive Director or CEO', 'The senior technical field technician', 'The fleet administration officer', 'The payroll clerk', 'A', 'High-level business development and corporate representation are handled by the CEO/Executive Director.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'What is the purpose of the annual corporate retreat organized by Executive Management?', 'To review annual performance and set strategic directions', 'To conduct technical training on battery wiring', 'To negotiate contracts with local suppliers', 'To audit local government tariff permissions', 'A', 'Retreats focus on corporate performance auditing, strategy building, and team alignment.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'How is risk management handled at the executive level?', 'Through a corporate risk register monitored quarterly', 'By choosing not to evaluate project safety parameters', 'By delegating all financial risk to local site workers', 'By maintaining no risk records in the ERP', 'A', 'Risk management uses a centralized risk register to track operational, financial, and regulatory items.', true),
('aaaaaaaa-0001-4000-a000-000000000004', 'Executive Management', 'What is the main objective of corporate social responsibility (CSR) in host communities?', 'To build long-term goodwill, support local schools, and provide clean water', 'To sell solar products at high premium prices', 'To replace local government administrators', 'To recruit technical engineers from other states', 'A', 'CSR focuses on supporting host communities with clean water access, schools, and building trust.', true);
